# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgentCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'object',
        'description': 'object',
        'status': 'object',
        'model_provider': 'ModelProvider',
        'model_name': 'object',
        'reasoning_profile': 'ReasoningTier',
        'memory_profile': 'object',
        'knowledge_scope': 'object',
        'home_space_id': 'object',
        'core_config': 'AgentCoreConfigInput'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'status': 'status',
        'model_provider': 'model_provider',
        'model_name': 'model_name',
        'reasoning_profile': 'reasoning_profile',
        'memory_profile': 'memory_profile',
        'knowledge_scope': 'knowledge_scope',
        'home_space_id': 'home_space_id',
        'core_config': 'core_config'
    }

    def __init__(self, name=None, description=None, status=None, model_provider=None, model_name=None, reasoning_profile=None, memory_profile=None, knowledge_scope=None, home_space_id=None, core_config=None):  # noqa: E501
        """AgentCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._status = None
        self._model_provider = None
        self._model_name = None
        self._reasoning_profile = None
        self._memory_profile = None
        self._knowledge_scope = None
        self._home_space_id = None
        self._core_config = None
        self.discriminator = None
        self.name = name
        if description is not None:
            self.description = description
        if status is not None:
            self.status = status
        if model_provider is not None:
            self.model_provider = model_provider
        if model_name is not None:
            self.model_name = model_name
        if reasoning_profile is not None:
            self.reasoning_profile = reasoning_profile
        if memory_profile is not None:
            self.memory_profile = memory_profile
        if knowledge_scope is not None:
            self.knowledge_scope = knowledge_scope
        if home_space_id is not None:
            self.home_space_id = home_space_id
        self.core_config = core_config

    @property
    def name(self):
        """Gets the name of this AgentCreateRequest.  # noqa: E501


        :return: The name of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AgentCreateRequest.


        :param name: The name of this AgentCreateRequest.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this AgentCreateRequest.  # noqa: E501

        Optional short agent description.  # noqa: E501

        :return: The description of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AgentCreateRequest.

        Optional short agent description.  # noqa: E501

        :param description: The description of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def status(self):
        """Gets the status of this AgentCreateRequest.  # noqa: E501

        Hosted lifecycle flag (e.g. active, paused).  # noqa: E501

        :return: The status of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AgentCreateRequest.

        Hosted lifecycle flag (e.g. active, paused).  # noqa: E501

        :param status: The status of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._status = status

    @property
    def model_provider(self):
        """Gets the model_provider of this AgentCreateRequest.  # noqa: E501

        Model provider for this agent. Defaults to the platform fallback provider (`openai`).  # noqa: E501

        :return: The model_provider of this AgentCreateRequest.  # noqa: E501
        :rtype: ModelProvider
        """
        return self._model_provider

    @model_provider.setter
    def model_provider(self, model_provider):
        """Sets the model_provider of this AgentCreateRequest.

        Model provider for this agent. Defaults to the platform fallback provider (`openai`).  # noqa: E501

        :param model_provider: The model_provider of this AgentCreateRequest.  # noqa: E501
        :type: ModelProvider
        """

        self._model_provider = model_provider

    @property
    def model_name(self):
        """Gets the model_name of this AgentCreateRequest.  # noqa: E501

        Provider-specific model id (maps to `AgentConfig.model`). Defaults to the platform fallback model.  # noqa: E501

        :return: The model_name of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this AgentCreateRequest.

        Provider-specific model id (maps to `AgentConfig.model`). Defaults to the platform fallback model.  # noqa: E501

        :param model_name: The model_name of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._model_name = model_name

    @property
    def reasoning_profile(self):
        """Gets the reasoning_profile of this AgentCreateRequest.  # noqa: E501

        Hosted reasoning tier applied to runs dispatched for this agent.  # noqa: E501

        :return: The reasoning_profile of this AgentCreateRequest.  # noqa: E501
        :rtype: ReasoningTier
        """
        return self._reasoning_profile

    @reasoning_profile.setter
    def reasoning_profile(self, reasoning_profile):
        """Sets the reasoning_profile of this AgentCreateRequest.

        Hosted reasoning tier applied to runs dispatched for this agent.  # noqa: E501

        :param reasoning_profile: The reasoning_profile of this AgentCreateRequest.  # noqa: E501
        :type: ReasoningTier
        """

        self._reasoning_profile = reasoning_profile

    @property
    def memory_profile(self):
        """Gets the memory_profile of this AgentCreateRequest.  # noqa: E501

        Platform memory integration preset (e.g. default, rich).  # noqa: E501

        :return: The memory_profile of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._memory_profile

    @memory_profile.setter
    def memory_profile(self, memory_profile):
        """Sets the memory_profile of this AgentCreateRequest.

        Platform memory integration preset (e.g. default, rich).  # noqa: E501

        :param memory_profile: The memory_profile of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._memory_profile = memory_profile

    @property
    def knowledge_scope(self):
        """Gets the knowledge_scope of this AgentCreateRequest.  # noqa: E501

        Knowledge isolation label stored on the agent row for the runtime.  # noqa: E501

        :return: The knowledge_scope of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._knowledge_scope

    @knowledge_scope.setter
    def knowledge_scope(self, knowledge_scope):
        """Sets the knowledge_scope of this AgentCreateRequest.

        Knowledge isolation label stored on the agent row for the runtime.  # noqa: E501

        :param knowledge_scope: The knowledge_scope of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._knowledge_scope = knowledge_scope

    @property
    def home_space_id(self):
        """Gets the home_space_id of this AgentCreateRequest.  # noqa: E501

        Optional home space (`public.spaces`) for this agent. The composite FK `(tenant_id, home_space_id)` pins it to the caller's tenant.  # noqa: E501

        :return: The home_space_id of this AgentCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._home_space_id

    @home_space_id.setter
    def home_space_id(self, home_space_id):
        """Sets the home_space_id of this AgentCreateRequest.

        Optional home space (`public.spaces`) for this agent. The composite FK `(tenant_id, home_space_id)` pins it to the caller's tenant.  # noqa: E501

        :param home_space_id: The home_space_id of this AgentCreateRequest.  # noqa: E501
        :type: object
        """

        self._home_space_id = home_space_id

    @property
    def core_config(self):
        """Gets the core_config of this AgentCreateRequest.  # noqa: E501

        hyperstruck-core-aligned configuration blob. Required on create so every agent has explicit instructions.  # noqa: E501

        :return: The core_config of this AgentCreateRequest.  # noqa: E501
        :rtype: AgentCoreConfigInput
        """
        return self._core_config

    @core_config.setter
    def core_config(self, core_config):
        """Sets the core_config of this AgentCreateRequest.

        hyperstruck-core-aligned configuration blob. Required on create so every agent has explicit instructions.  # noqa: E501

        :param core_config: The core_config of this AgentCreateRequest.  # noqa: E501
        :type: AgentCoreConfigInput
        """
        if core_config is None:
            raise ValueError("Invalid value for `core_config`, must not be `None`")  # noqa: E501

        self._core_config = core_config

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgentCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgentCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
