# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnswerSubject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'claims_held': 'object',
        'entity_id': 'object',
        'entity_name': 'object',
        'matched_via': 'object'
    }

    attribute_map = {
        'claims_held': 'claims_held',
        'entity_id': 'entity_id',
        'entity_name': 'entity_name',
        'matched_via': 'matched_via'
    }

    def __init__(self, claims_held=None, entity_id=None, entity_name=None, matched_via=None):  # noqa: E501
        """AnswerSubject - a model defined in Swagger"""  # noqa: E501
        self._claims_held = None
        self._entity_id = None
        self._entity_name = None
        self._matched_via = None
        self.discriminator = None
        if claims_held is not None:
            self.claims_held = claims_held
        self.entity_id = entity_id
        self.entity_name = entity_name
        if matched_via is not None:
            self.matched_via = matched_via

    @property
    def claims_held(self):
        """Gets the claims_held of this AnswerSubject.  # noqa: E501

        How many claims this subject holds across the whole selected set, not on this page. Null when the counts could not be taken, which is stated as a `shelf_unavailable` silence naming `set_counts`; a zero here is a measured zero.  # noqa: E501

        :return: The claims_held of this AnswerSubject.  # noqa: E501
        :rtype: object
        """
        return self._claims_held

    @claims_held.setter
    def claims_held(self, claims_held):
        """Sets the claims_held of this AnswerSubject.

        How many claims this subject holds across the whole selected set, not on this page. Null when the counts could not be taken, which is stated as a `shelf_unavailable` silence naming `set_counts`; a zero here is a measured zero.  # noqa: E501

        :param claims_held: The claims_held of this AnswerSubject.  # noqa: E501
        :type: object
        """

        self._claims_held = claims_held

    @property
    def entity_id(self):
        """Gets the entity_id of this AnswerSubject.  # noqa: E501


        :return: The entity_id of this AnswerSubject.  # noqa: E501
        :rtype: object
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this AnswerSubject.


        :param entity_id: The entity_id of this AnswerSubject.  # noqa: E501
        :type: object
        """
        if entity_id is None:
            raise ValueError("Invalid value for `entity_id`, must not be `None`")  # noqa: E501

        self._entity_id = entity_id

    @property
    def entity_name(self):
        """Gets the entity_name of this AnswerSubject.  # noqa: E501


        :return: The entity_name of this AnswerSubject.  # noqa: E501
        :rtype: object
        """
        return self._entity_name

    @entity_name.setter
    def entity_name(self, entity_name):
        """Sets the entity_name of this AnswerSubject.


        :param entity_name: The entity_name of this AnswerSubject.  # noqa: E501
        :type: object
        """
        if entity_name is None:
            raise ValueError("Invalid value for `entity_name`, must not be `None`")  # noqa: E501

        self._entity_name = entity_name

    @property
    def matched_via(self):
        """Gets the matched_via of this AnswerSubject.  # noqa: E501


        :return: The matched_via of this AnswerSubject.  # noqa: E501
        :rtype: object
        """
        return self._matched_via

    @matched_via.setter
    def matched_via(self, matched_via):
        """Sets the matched_via of this AnswerSubject.


        :param matched_via: The matched_via of this AnswerSubject.  # noqa: E501
        :type: object
        """

        self._matched_via = matched_via

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnswerSubject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnswerSubject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
