# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnswerSelection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_question_truncated': 'object',
        'non_participating_terms': 'object',
        'participating_terms': 'object'
    }

    attribute_map = {
        'is_question_truncated': 'is_question_truncated',
        'non_participating_terms': 'non_participating_terms',
        'participating_terms': 'participating_terms'
    }

    def __init__(self, is_question_truncated=None, non_participating_terms=None, participating_terms=None):  # noqa: E501
        """AnswerSelection - a model defined in Swagger"""  # noqa: E501
        self._is_question_truncated = None
        self._non_participating_terms = None
        self._participating_terms = None
        self.discriminator = None
        if is_question_truncated is not None:
            self.is_question_truncated = is_question_truncated
        if non_participating_terms is not None:
            self.non_participating_terms = non_participating_terms
        if participating_terms is not None:
            self.participating_terms = participating_terms

    @property
    def is_question_truncated(self):
        """Gets the is_question_truncated of this AnswerSelection.  # noqa: E501

        True when the question was longer than the scan bound, so the non-participating list is a lower bound rather than all of it.  # noqa: E501

        :return: The is_question_truncated of this AnswerSelection.  # noqa: E501
        :rtype: object
        """
        return self._is_question_truncated

    @is_question_truncated.setter
    def is_question_truncated(self, is_question_truncated):
        """Sets the is_question_truncated of this AnswerSelection.

        True when the question was longer than the scan bound, so the non-participating list is a lower bound rather than all of it.  # noqa: E501

        :param is_question_truncated: The is_question_truncated of this AnswerSelection.  # noqa: E501
        :type: object
        """

        self._is_question_truncated = is_question_truncated

    @property
    def non_participating_terms(self):
        """Gets the non_participating_terms of this AnswerSelection.  # noqa: E501


        :return: The non_participating_terms of this AnswerSelection.  # noqa: E501
        :rtype: object
        """
        return self._non_participating_terms

    @non_participating_terms.setter
    def non_participating_terms(self, non_participating_terms):
        """Sets the non_participating_terms of this AnswerSelection.


        :param non_participating_terms: The non_participating_terms of this AnswerSelection.  # noqa: E501
        :type: object
        """

        self._non_participating_terms = non_participating_terms

    @property
    def participating_terms(self):
        """Gets the participating_terms of this AnswerSelection.  # noqa: E501


        :return: The participating_terms of this AnswerSelection.  # noqa: E501
        :rtype: object
        """
        return self._participating_terms

    @participating_terms.setter
    def participating_terms(self, participating_terms):
        """Sets the participating_terms of this AnswerSelection.


        :param participating_terms: The participating_terms of this AnswerSelection.  # noqa: E501
        :type: object
        """

        self._participating_terms = participating_terms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnswerSelection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnswerSelection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
