# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChartDataRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'window': 'object',
        'as_of': 'object'
    }

    attribute_map = {
        'window': 'window',
        'as_of': 'as_of'
    }

    def __init__(self, window=None, as_of=None):  # noqa: E501
        """ChartDataRequest - a model defined in Swagger"""  # noqa: E501
        self._window = None
        self._as_of = None
        self.discriminator = None
        if window is not None:
            self.window = window
        if as_of is not None:
            self.as_of = as_of

    @property
    def window(self):
        """Gets the window of this ChartDataRequest.  # noqa: E501


        :return: The window of this ChartDataRequest.  # noqa: E501
        :rtype: object
        """
        return self._window

    @window.setter
    def window(self, window):
        """Sets the window of this ChartDataRequest.


        :param window: The window of this ChartDataRequest.  # noqa: E501
        :type: object
        """

        self._window = window

    @property
    def as_of(self):
        """Gets the as_of of this ChartDataRequest.  # noqa: E501


        :return: The as_of of this ChartDataRequest.  # noqa: E501
        :rtype: object
        """
        return self._as_of

    @as_of.setter
    def as_of(self, as_of):
        """Sets the as_of of this ChartDataRequest.


        :param as_of: The as_of of this ChartDataRequest.  # noqa: E501
        :type: object
        """

        self._as_of = as_of

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChartDataRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChartDataRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
