# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChartCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'object',
        'query_binding': 'QueryBinding',
        'space_id': 'object',
        'title': 'object',
        'viz_spec': 'object'
    }

    attribute_map = {
        'description': 'description',
        'query_binding': 'query_binding',
        'space_id': 'space_id',
        'title': 'title',
        'viz_spec': 'viz_spec'
    }

    def __init__(self, description=None, query_binding=None, space_id=None, title=None, viz_spec=None):  # noqa: E501
        """ChartCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._query_binding = None
        self._space_id = None
        self._title = None
        self._viz_spec = None
        self.discriminator = None
        if description is not None:
            self.description = description
        self.query_binding = query_binding
        self.space_id = space_id
        self.title = title
        self.viz_spec = viz_spec

    @property
    def description(self):
        """Gets the description of this ChartCreateRequest.  # noqa: E501


        :return: The description of this ChartCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ChartCreateRequest.


        :param description: The description of this ChartCreateRequest.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def query_binding(self):
        """Gets the query_binding of this ChartCreateRequest.  # noqa: E501


        :return: The query_binding of this ChartCreateRequest.  # noqa: E501
        :rtype: QueryBinding
        """
        return self._query_binding

    @query_binding.setter
    def query_binding(self, query_binding):
        """Sets the query_binding of this ChartCreateRequest.


        :param query_binding: The query_binding of this ChartCreateRequest.  # noqa: E501
        :type: QueryBinding
        """
        if query_binding is None:
            raise ValueError("Invalid value for `query_binding`, must not be `None`")  # noqa: E501

        self._query_binding = query_binding

    @property
    def space_id(self):
        """Gets the space_id of this ChartCreateRequest.  # noqa: E501


        :return: The space_id of this ChartCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._space_id

    @space_id.setter
    def space_id(self, space_id):
        """Sets the space_id of this ChartCreateRequest.


        :param space_id: The space_id of this ChartCreateRequest.  # noqa: E501
        :type: object
        """
        if space_id is None:
            raise ValueError("Invalid value for `space_id`, must not be `None`")  # noqa: E501

        self._space_id = space_id

    @property
    def title(self):
        """Gets the title of this ChartCreateRequest.  # noqa: E501


        :return: The title of this ChartCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ChartCreateRequest.


        :param title: The title of this ChartCreateRequest.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def viz_spec(self):
        """Gets the viz_spec of this ChartCreateRequest.  # noqa: E501


        :return: The viz_spec of this ChartCreateRequest.  # noqa: E501
        :rtype: object
        """
        return self._viz_spec

    @viz_spec.setter
    def viz_spec(self, viz_spec):
        """Sets the viz_spec of this ChartCreateRequest.


        :param viz_spec: The viz_spec of this ChartCreateRequest.  # noqa: E501
        :type: object
        """
        if viz_spec is None:
            raise ValueError("Invalid value for `viz_spec`, must not be `None`")  # noqa: E501

        self._viz_spec = viz_spec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChartCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChartCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
