# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CitationsReport(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'guarantee': 'ReadGuarantee',
        'unavailable_reason': 'object'
    }

    attribute_map = {
        'guarantee': 'guarantee',
        'unavailable_reason': 'unavailable_reason'
    }

    def __init__(self, guarantee=None, unavailable_reason=None):  # noqa: E501
        """CitationsReport - a model defined in Swagger"""  # noqa: E501
        self._guarantee = None
        self._unavailable_reason = None
        self.discriminator = None
        self.guarantee = guarantee
        if unavailable_reason is not None:
            self.unavailable_reason = unavailable_reason

    @property
    def guarantee(self):
        """Gets the guarantee of this CitationsReport.  # noqa: E501


        :return: The guarantee of this CitationsReport.  # noqa: E501
        :rtype: ReadGuarantee
        """
        return self._guarantee

    @guarantee.setter
    def guarantee(self, guarantee):
        """Sets the guarantee of this CitationsReport.


        :param guarantee: The guarantee of this CitationsReport.  # noqa: E501
        :type: ReadGuarantee
        """
        if guarantee is None:
            raise ValueError("Invalid value for `guarantee`, must not be `None`")  # noqa: E501

        self._guarantee = guarantee

    @property
    def unavailable_reason(self):
        """Gets the unavailable_reason of this CitationsReport.  # noqa: E501

        Why no row's sources were read. Null when the lookup ran.  # noqa: E501

        :return: The unavailable_reason of this CitationsReport.  # noqa: E501
        :rtype: object
        """
        return self._unavailable_reason

    @unavailable_reason.setter
    def unavailable_reason(self, unavailable_reason):
        """Sets the unavailable_reason of this CitationsReport.

        Why no row's sources were read. Null when the lookup ran.  # noqa: E501

        :param unavailable_reason: The unavailable_reason of this CitationsReport.  # noqa: E501
        :type: object
        """

        self._unavailable_reason = unavailable_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CitationsReport, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CitationsReport):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
