# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ClaimWipeResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_id': 'object',
        'attributes_removed': 'object',
        'claims_erased': 'object',
        'entities_erased': 'object',
        'has_residue': 'object',
        'remaining_entities': 'object',
        'request_ids': 'object'
    }

    attribute_map = {
        'agent_id': 'agent_id',
        'attributes_removed': 'attributes_removed',
        'claims_erased': 'claims_erased',
        'entities_erased': 'entities_erased',
        'has_residue': 'has_residue',
        'remaining_entities': 'remaining_entities',
        'request_ids': 'request_ids'
    }

    def __init__(self, agent_id=None, attributes_removed=None, claims_erased=None, entities_erased=None, has_residue=None, remaining_entities=None, request_ids=None):  # noqa: E501
        """ClaimWipeResponse - a model defined in Swagger"""  # noqa: E501
        self._agent_id = None
        self._attributes_removed = None
        self._claims_erased = None
        self._entities_erased = None
        self._has_residue = None
        self._remaining_entities = None
        self._request_ids = None
        self.discriminator = None
        self.agent_id = agent_id
        self.attributes_removed = attributes_removed
        self.claims_erased = claims_erased
        self.entities_erased = entities_erased
        self.has_residue = has_residue
        self.remaining_entities = remaining_entities
        self.request_ids = request_ids

    @property
    def agent_id(self):
        """Gets the agent_id of this ClaimWipeResponse.  # noqa: E501


        :return: The agent_id of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this ClaimWipeResponse.


        :param agent_id: The agent_id of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if agent_id is None:
            raise ValueError("Invalid value for `agent_id`, must not be `None`")  # noqa: E501

        self._agent_id = agent_id

    @property
    def attributes_removed(self):
        """Gets the attributes_removed of this ClaimWipeResponse.  # noqa: E501


        :return: The attributes_removed of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._attributes_removed

    @attributes_removed.setter
    def attributes_removed(self, attributes_removed):
        """Sets the attributes_removed of this ClaimWipeResponse.


        :param attributes_removed: The attributes_removed of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if attributes_removed is None:
            raise ValueError("Invalid value for `attributes_removed`, must not be `None`")  # noqa: E501

        self._attributes_removed = attributes_removed

    @property
    def claims_erased(self):
        """Gets the claims_erased of this ClaimWipeResponse.  # noqa: E501


        :return: The claims_erased of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._claims_erased

    @claims_erased.setter
    def claims_erased(self, claims_erased):
        """Sets the claims_erased of this ClaimWipeResponse.


        :param claims_erased: The claims_erased of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if claims_erased is None:
            raise ValueError("Invalid value for `claims_erased`, must not be `None`")  # noqa: E501

        self._claims_erased = claims_erased

    @property
    def entities_erased(self):
        """Gets the entities_erased of this ClaimWipeResponse.  # noqa: E501


        :return: The entities_erased of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._entities_erased

    @entities_erased.setter
    def entities_erased(self, entities_erased):
        """Sets the entities_erased of this ClaimWipeResponse.


        :param entities_erased: The entities_erased of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if entities_erased is None:
            raise ValueError("Invalid value for `entities_erased`, must not be `None`")  # noqa: E501

        self._entities_erased = entities_erased

    @property
    def has_residue(self):
        """Gets the has_residue of this ClaimWipeResponse.  # noqa: E501


        :return: The has_residue of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._has_residue

    @has_residue.setter
    def has_residue(self, has_residue):
        """Sets the has_residue of this ClaimWipeResponse.


        :param has_residue: The has_residue of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if has_residue is None:
            raise ValueError("Invalid value for `has_residue`, must not be `None`")  # noqa: E501

        self._has_residue = has_residue

    @property
    def remaining_entities(self):
        """Gets the remaining_entities of this ClaimWipeResponse.  # noqa: E501


        :return: The remaining_entities of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._remaining_entities

    @remaining_entities.setter
    def remaining_entities(self, remaining_entities):
        """Sets the remaining_entities of this ClaimWipeResponse.


        :param remaining_entities: The remaining_entities of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if remaining_entities is None:
            raise ValueError("Invalid value for `remaining_entities`, must not be `None`")  # noqa: E501

        self._remaining_entities = remaining_entities

    @property
    def request_ids(self):
        """Gets the request_ids of this ClaimWipeResponse.  # noqa: E501


        :return: The request_ids of this ClaimWipeResponse.  # noqa: E501
        :rtype: object
        """
        return self._request_ids

    @request_ids.setter
    def request_ids(self, request_ids):
        """Sets the request_ids of this ClaimWipeResponse.


        :param request_ids: The request_ids of this ClaimWipeResponse.  # noqa: E501
        :type: object
        """
        if request_ids is None:
            raise ValueError("Invalid value for `request_ids`, must not be `None`")  # noqa: E501

        self._request_ids = request_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClaimWipeResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClaimWipeResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
