# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DashboardItemInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chart_id': 'object',
        'row_index': 'object',
        'col_index': 'object',
        'col_span': 'object',
        'sort_key': 'object'
    }

    attribute_map = {
        'chart_id': 'chart_id',
        'row_index': 'row_index',
        'col_index': 'col_index',
        'col_span': 'col_span',
        'sort_key': 'sort_key'
    }

    def __init__(self, chart_id=None, row_index=None, col_index=None, col_span=None, sort_key=None):  # noqa: E501
        """DashboardItemInput - a model defined in Swagger"""  # noqa: E501
        self._chart_id = None
        self._row_index = None
        self._col_index = None
        self._col_span = None
        self._sort_key = None
        self.discriminator = None
        self.chart_id = chart_id
        self.row_index = row_index
        self.col_index = col_index
        if col_span is not None:
            self.col_span = col_span
        if sort_key is not None:
            self.sort_key = sort_key

    @property
    def chart_id(self):
        """Gets the chart_id of this DashboardItemInput.  # noqa: E501


        :return: The chart_id of this DashboardItemInput.  # noqa: E501
        :rtype: object
        """
        return self._chart_id

    @chart_id.setter
    def chart_id(self, chart_id):
        """Sets the chart_id of this DashboardItemInput.


        :param chart_id: The chart_id of this DashboardItemInput.  # noqa: E501
        :type: object
        """
        if chart_id is None:
            raise ValueError("Invalid value for `chart_id`, must not be `None`")  # noqa: E501

        self._chart_id = chart_id

    @property
    def row_index(self):
        """Gets the row_index of this DashboardItemInput.  # noqa: E501


        :return: The row_index of this DashboardItemInput.  # noqa: E501
        :rtype: object
        """
        return self._row_index

    @row_index.setter
    def row_index(self, row_index):
        """Sets the row_index of this DashboardItemInput.


        :param row_index: The row_index of this DashboardItemInput.  # noqa: E501
        :type: object
        """
        if row_index is None:
            raise ValueError("Invalid value for `row_index`, must not be `None`")  # noqa: E501

        self._row_index = row_index

    @property
    def col_index(self):
        """Gets the col_index of this DashboardItemInput.  # noqa: E501


        :return: The col_index of this DashboardItemInput.  # noqa: E501
        :rtype: object
        """
        return self._col_index

    @col_index.setter
    def col_index(self, col_index):
        """Sets the col_index of this DashboardItemInput.


        :param col_index: The col_index of this DashboardItemInput.  # noqa: E501
        :type: object
        """
        if col_index is None:
            raise ValueError("Invalid value for `col_index`, must not be `None`")  # noqa: E501

        self._col_index = col_index

    @property
    def col_span(self):
        """Gets the col_span of this DashboardItemInput.  # noqa: E501


        :return: The col_span of this DashboardItemInput.  # noqa: E501
        :rtype: object
        """
        return self._col_span

    @col_span.setter
    def col_span(self, col_span):
        """Sets the col_span of this DashboardItemInput.


        :param col_span: The col_span of this DashboardItemInput.  # noqa: E501
        :type: object
        """

        self._col_span = col_span

    @property
    def sort_key(self):
        """Gets the sort_key of this DashboardItemInput.  # noqa: E501


        :return: The sort_key of this DashboardItemInput.  # noqa: E501
        :rtype: object
        """
        return self._sort_key

    @sort_key.setter
    def sort_key(self, sort_key):
        """Sets the sort_key of this DashboardItemInput.


        :param sort_key: The sort_key of this DashboardItemInput.  # noqa: E501
        :type: object
        """

        self._sort_key = sort_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DashboardItemInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DashboardItemInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
