# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DistillRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_name': 'object',
        'evaluation': 'object',
        'evidence': 'object',
        'goal': 'object',
        'max_learnings': 'object',
        'occurred_at': 'object',
        'org_id': 'object',
        'outcome': 'DistillOutcomeModel',
        'run_id': 'object',
        'source_framework': 'object',
        'synthesis_notes': 'object'
    }

    attribute_map = {
        'agent_name': 'agent_name',
        'evaluation': 'evaluation',
        'evidence': 'evidence',
        'goal': 'goal',
        'max_learnings': 'max_learnings',
        'occurred_at': 'occurred_at',
        'org_id': 'org_id',
        'outcome': 'outcome',
        'run_id': 'run_id',
        'source_framework': 'source_framework',
        'synthesis_notes': 'synthesis_notes'
    }

    def __init__(self, agent_name=None, evaluation=None, evidence=None, goal=None, max_learnings=None, occurred_at=None, org_id=None, outcome=None, run_id=None, source_framework=None, synthesis_notes=None):  # noqa: E501
        """DistillRequest - a model defined in Swagger"""  # noqa: E501
        self._agent_name = None
        self._evaluation = None
        self._evidence = None
        self._goal = None
        self._max_learnings = None
        self._occurred_at = None
        self._org_id = None
        self._outcome = None
        self._run_id = None
        self._source_framework = None
        self._synthesis_notes = None
        self.discriminator = None
        self.agent_name = agent_name
        if evaluation is not None:
            self.evaluation = evaluation
        if evidence is not None:
            self.evidence = evidence
        self.goal = goal
        if max_learnings is not None:
            self.max_learnings = max_learnings
        if occurred_at is not None:
            self.occurred_at = occurred_at
        if org_id is not None:
            self.org_id = org_id
        self.outcome = outcome
        self.run_id = run_id
        if source_framework is not None:
            self.source_framework = source_framework
        if synthesis_notes is not None:
            self.synthesis_notes = synthesis_notes

    @property
    def agent_name(self):
        """Gets the agent_name of this DistillRequest.  # noqa: E501

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, a write-scoped call (`agents:write`) creates a minimal learning agent in your tenant. `POST /resolve` with only `agents:read` looks up an existing name and does not insert. Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :return: The agent_name of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_name

    @agent_name.setter
    def agent_name(self, agent_name):
        """Sets the agent_name of this DistillRequest.

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, a write-scoped call (`agents:write`) creates a minimal learning agent in your tenant. `POST /resolve` with only `agents:read` looks up an existing name and does not insert. Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :param agent_name: The agent_name of this DistillRequest.  # noqa: E501
        :type: object
        """
        if agent_name is None:
            raise ValueError("Invalid value for `agent_name`, must not be `None`")  # noqa: E501

        self._agent_name = agent_name

    @property
    def evaluation(self):
        """Gets the evaluation of this DistillRequest.  # noqa: E501

        Reviewer verdict or contrast aid; folded into the grounding corpus.  # noqa: E501

        :return: The evaluation of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._evaluation

    @evaluation.setter
    def evaluation(self, evaluation):
        """Sets the evaluation of this DistillRequest.

        Reviewer verdict or contrast aid; folded into the grounding corpus.  # noqa: E501

        :param evaluation: The evaluation of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._evaluation = evaluation

    @property
    def evidence(self):
        """Gets the evidence of this DistillRequest.  # noqa: E501


        :return: The evidence of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._evidence

    @evidence.setter
    def evidence(self, evidence):
        """Sets the evidence of this DistillRequest.


        :param evidence: The evidence of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._evidence = evidence

    @property
    def goal(self):
        """Gets the goal of this DistillRequest.  # noqa: E501

        The extraction intent.  # noqa: E501

        :return: The goal of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._goal

    @goal.setter
    def goal(self, goal):
        """Sets the goal of this DistillRequest.

        The extraction intent.  # noqa: E501

        :param goal: The goal of this DistillRequest.  # noqa: E501
        :type: object
        """
        if goal is None:
            raise ValueError("Invalid value for `goal`, must not be `None`")  # noqa: E501

        self._goal = goal

    @property
    def max_learnings(self):
        """Gets the max_learnings of this DistillRequest.  # noqa: E501

        Maximum number of learnings to extract from this distill job. Defaults to 10; lower for sparse corpora or raise for large, dense documents.  # noqa: E501

        :return: The max_learnings of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._max_learnings

    @max_learnings.setter
    def max_learnings(self, max_learnings):
        """Sets the max_learnings of this DistillRequest.

        Maximum number of learnings to extract from this distill job. Defaults to 10; lower for sparse corpora or raise for large, dense documents.  # noqa: E501

        :param max_learnings: The max_learnings of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._max_learnings = max_learnings

    @property
    def occurred_at(self):
        """Gets the occurred_at of this DistillRequest.  # noqa: E501


        :return: The occurred_at of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._occurred_at

    @occurred_at.setter
    def occurred_at(self, occurred_at):
        """Sets the occurred_at of this DistillRequest.


        :param occurred_at: The occurred_at of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._occurred_at = occurred_at

    @property
    def org_id(self):
        """Gets the org_id of this DistillRequest.  # noqa: E501

        Optional caller-owned organisation reference.  # noqa: E501

        :return: The org_id of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this DistillRequest.

        Optional caller-owned organisation reference.  # noqa: E501

        :param org_id: The org_id of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._org_id = org_id

    @property
    def outcome(self):
        """Gets the outcome of this DistillRequest.  # noqa: E501


        :return: The outcome of this DistillRequest.  # noqa: E501
        :rtype: DistillOutcomeModel
        """
        return self._outcome

    @outcome.setter
    def outcome(self, outcome):
        """Sets the outcome of this DistillRequest.


        :param outcome: The outcome of this DistillRequest.  # noqa: E501
        :type: DistillOutcomeModel
        """
        if outcome is None:
            raise ValueError("Invalid value for `outcome`, must not be `None`")  # noqa: E501

        self._outcome = outcome

    @property
    def run_id(self):
        """Gets the run_id of this DistillRequest.  # noqa: E501

        Caller-created idempotency and tracing identifier. It must start with `distill:` and does not reference a hosted run.  # noqa: E501

        :return: The run_id of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this DistillRequest.

        Caller-created idempotency and tracing identifier. It must start with `distill:` and does not reference a hosted run.  # noqa: E501

        :param run_id: The run_id of this DistillRequest.  # noqa: E501
        :type: object
        """
        if run_id is None:
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501

        self._run_id = run_id

    @property
    def source_framework(self):
        """Gets the source_framework of this DistillRequest.  # noqa: E501


        :return: The source_framework of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._source_framework

    @source_framework.setter
    def source_framework(self, source_framework):
        """Sets the source_framework of this DistillRequest.


        :param source_framework: The source_framework of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._source_framework = source_framework

    @property
    def synthesis_notes(self):
        """Gets the synthesis_notes of this DistillRequest.  # noqa: E501


        :return: The synthesis_notes of this DistillRequest.  # noqa: E501
        :rtype: object
        """
        return self._synthesis_notes

    @synthesis_notes.setter
    def synthesis_notes(self, synthesis_notes):
        """Sets the synthesis_notes of this DistillRequest.


        :param synthesis_notes: The synthesis_notes of this DistillRequest.  # noqa: E501
        :type: object
        """

        self._synthesis_notes = synthesis_notes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DistillRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DistillRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
