# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DocumentCitationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'doc_id': 'object',
        'end': 'object',
        'segmenter_version': 'object',
        'start': 'object',
        'text_sha256': 'object',
        'unit_index': 'object'
    }

    attribute_map = {
        'doc_id': 'doc_id',
        'end': 'end',
        'segmenter_version': 'segmenter_version',
        'start': 'start',
        'text_sha256': 'text_sha256',
        'unit_index': 'unit_index'
    }

    def __init__(self, doc_id=None, end=None, segmenter_version=None, start=None, text_sha256=None, unit_index=None):  # noqa: E501
        """DocumentCitationResponse - a model defined in Swagger"""  # noqa: E501
        self._doc_id = None
        self._end = None
        self._segmenter_version = None
        self._start = None
        self._text_sha256 = None
        self._unit_index = None
        self.discriminator = None
        self.doc_id = doc_id
        self.end = end
        self.segmenter_version = segmenter_version
        self.start = start
        self.text_sha256 = text_sha256
        self.unit_index = unit_index

    @property
    def doc_id(self):
        """Gets the doc_id of this DocumentCitationResponse.  # noqa: E501


        :return: The doc_id of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._doc_id

    @doc_id.setter
    def doc_id(self, doc_id):
        """Sets the doc_id of this DocumentCitationResponse.


        :param doc_id: The doc_id of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if doc_id is None:
            raise ValueError("Invalid value for `doc_id`, must not be `None`")  # noqa: E501

        self._doc_id = doc_id

    @property
    def end(self):
        """Gets the end of this DocumentCitationResponse.  # noqa: E501


        :return: The end of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this DocumentCitationResponse.


        :param end: The end of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if end is None:
            raise ValueError("Invalid value for `end`, must not be `None`")  # noqa: E501

        self._end = end

    @property
    def segmenter_version(self):
        """Gets the segmenter_version of this DocumentCitationResponse.  # noqa: E501


        :return: The segmenter_version of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._segmenter_version

    @segmenter_version.setter
    def segmenter_version(self, segmenter_version):
        """Sets the segmenter_version of this DocumentCitationResponse.


        :param segmenter_version: The segmenter_version of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if segmenter_version is None:
            raise ValueError("Invalid value for `segmenter_version`, must not be `None`")  # noqa: E501

        self._segmenter_version = segmenter_version

    @property
    def start(self):
        """Gets the start of this DocumentCitationResponse.  # noqa: E501


        :return: The start of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this DocumentCitationResponse.


        :param start: The start of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def text_sha256(self):
        """Gets the text_sha256 of this DocumentCitationResponse.  # noqa: E501


        :return: The text_sha256 of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._text_sha256

    @text_sha256.setter
    def text_sha256(self, text_sha256):
        """Sets the text_sha256 of this DocumentCitationResponse.


        :param text_sha256: The text_sha256 of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if text_sha256 is None:
            raise ValueError("Invalid value for `text_sha256`, must not be `None`")  # noqa: E501

        self._text_sha256 = text_sha256

    @property
    def unit_index(self):
        """Gets the unit_index of this DocumentCitationResponse.  # noqa: E501


        :return: The unit_index of this DocumentCitationResponse.  # noqa: E501
        :rtype: object
        """
        return self._unit_index

    @unit_index.setter
    def unit_index(self, unit_index):
        """Sets the unit_index of this DocumentCitationResponse.


        :param unit_index: The unit_index of this DocumentCitationResponse.  # noqa: E501
        :type: object
        """
        if unit_index is None:
            raise ValueError("Invalid value for `unit_index`, must not be `None`")  # noqa: E501

        self._unit_index = unit_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentCitationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentCitationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
