# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GuardrailsConfigInput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pii': 'object',
        'prompt_injection': 'object'
    }

    attribute_map = {
        'pii': 'pii',
        'prompt_injection': 'prompt_injection'
    }

    def __init__(self, pii=None, prompt_injection=None):  # noqa: E501
        """GuardrailsConfigInput - a model defined in Swagger"""  # noqa: E501
        self._pii = None
        self._prompt_injection = None
        self.discriminator = None
        if pii is not None:
            self.pii = pii
        if prompt_injection is not None:
            self.prompt_injection = prompt_injection

    @property
    def pii(self):
        """Gets the pii of this GuardrailsConfigInput.  # noqa: E501

        PII guardrail configuration (Presidio)  # noqa: E501

        :return: The pii of this GuardrailsConfigInput.  # noqa: E501
        :rtype: object
        """
        return self._pii

    @pii.setter
    def pii(self, pii):
        """Sets the pii of this GuardrailsConfigInput.

        PII guardrail configuration (Presidio)  # noqa: E501

        :param pii: The pii of this GuardrailsConfigInput.  # noqa: E501
        :type: object
        """

        self._pii = pii

    @property
    def prompt_injection(self):
        """Gets the prompt_injection of this GuardrailsConfigInput.  # noqa: E501

        Prompt-injection / jailbreak guardrail configuration  # noqa: E501

        :return: The prompt_injection of this GuardrailsConfigInput.  # noqa: E501
        :rtype: object
        """
        return self._prompt_injection

    @prompt_injection.setter
    def prompt_injection(self, prompt_injection):
        """Sets the prompt_injection of this GuardrailsConfigInput.

        Prompt-injection / jailbreak guardrail configuration  # noqa: E501

        :param prompt_injection: The prompt_injection of this GuardrailsConfigInput.  # noqa: E501
        :type: object
        """

        self._prompt_injection = prompt_injection

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GuardrailsConfigInput, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GuardrailsConfigInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
