# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HostLoopClosure(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host': 'object',
        'resolved': 'object',
        'offered': 'object',
        'observed': 'object',
        'reinforced': 'object',
        'half_open': 'object',
        'in_flight': 'object',
        'loop_closure_rate': 'object',
        'half_open_rate': 'object',
        'avg_seconds_to_close': 'object'
    }

    attribute_map = {
        'host': 'host',
        'resolved': 'resolved',
        'offered': 'offered',
        'observed': 'observed',
        'reinforced': 'reinforced',
        'half_open': 'half_open',
        'in_flight': 'in_flight',
        'loop_closure_rate': 'loop_closure_rate',
        'half_open_rate': 'half_open_rate',
        'avg_seconds_to_close': 'avg_seconds_to_close'
    }

    def __init__(self, host=None, resolved=None, offered=None, observed=None, reinforced=None, half_open=None, in_flight=None, loop_closure_rate=None, half_open_rate=None, avg_seconds_to_close=None):  # noqa: E501
        """HostLoopClosure - a model defined in Swagger"""  # noqa: E501
        self._host = None
        self._resolved = None
        self._offered = None
        self._observed = None
        self._reinforced = None
        self._half_open = None
        self._in_flight = None
        self._loop_closure_rate = None
        self._half_open_rate = None
        self._avg_seconds_to_close = None
        self.discriminator = None
        self.host = host
        self.resolved = resolved
        self.offered = offered
        self.observed = observed
        self.reinforced = reinforced
        self.half_open = half_open
        if in_flight is not None:
            self.in_flight = in_flight
        self.loop_closure_rate = loop_closure_rate
        self.half_open_rate = half_open_rate
        if avg_seconds_to_close is not None:
            self.avg_seconds_to_close = avg_seconds_to_close

    @property
    def host(self):
        """Gets the host of this HostLoopClosure.  # noqa: E501


        :return: The host of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this HostLoopClosure.


        :param host: The host of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def resolved(self):
        """Gets the resolved of this HostLoopClosure.  # noqa: E501


        :return: The resolved of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._resolved

    @resolved.setter
    def resolved(self, resolved):
        """Sets the resolved of this HostLoopClosure.


        :param resolved: The resolved of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if resolved is None:
            raise ValueError("Invalid value for `resolved`, must not be `None`")  # noqa: E501

        self._resolved = resolved

    @property
    def offered(self):
        """Gets the offered of this HostLoopClosure.  # noqa: E501


        :return: The offered of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._offered

    @offered.setter
    def offered(self, offered):
        """Sets the offered of this HostLoopClosure.


        :param offered: The offered of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if offered is None:
            raise ValueError("Invalid value for `offered`, must not be `None`")  # noqa: E501

        self._offered = offered

    @property
    def observed(self):
        """Gets the observed of this HostLoopClosure.  # noqa: E501


        :return: The observed of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._observed

    @observed.setter
    def observed(self, observed):
        """Sets the observed of this HostLoopClosure.


        :param observed: The observed of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if observed is None:
            raise ValueError("Invalid value for `observed`, must not be `None`")  # noqa: E501

        self._observed = observed

    @property
    def reinforced(self):
        """Gets the reinforced of this HostLoopClosure.  # noqa: E501


        :return: The reinforced of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._reinforced

    @reinforced.setter
    def reinforced(self, reinforced):
        """Sets the reinforced of this HostLoopClosure.


        :param reinforced: The reinforced of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if reinforced is None:
            raise ValueError("Invalid value for `reinforced`, must not be `None`")  # noqa: E501

        self._reinforced = reinforced

    @property
    def half_open(self):
        """Gets the half_open of this HostLoopClosure.  # noqa: E501


        :return: The half_open of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._half_open

    @half_open.setter
    def half_open(self, half_open):
        """Sets the half_open of this HostLoopClosure.


        :param half_open: The half_open of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if half_open is None:
            raise ValueError("Invalid value for `half_open`, must not be `None`")  # noqa: E501

        self._half_open = half_open

    @property
    def in_flight(self):
        """Gets the in_flight of this HostLoopClosure.  # noqa: E501


        :return: The in_flight of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._in_flight

    @in_flight.setter
    def in_flight(self, in_flight):
        """Sets the in_flight of this HostLoopClosure.


        :param in_flight: The in_flight of this HostLoopClosure.  # noqa: E501
        :type: object
        """

        self._in_flight = in_flight

    @property
    def loop_closure_rate(self):
        """Gets the loop_closure_rate of this HostLoopClosure.  # noqa: E501


        :return: The loop_closure_rate of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._loop_closure_rate

    @loop_closure_rate.setter
    def loop_closure_rate(self, loop_closure_rate):
        """Sets the loop_closure_rate of this HostLoopClosure.


        :param loop_closure_rate: The loop_closure_rate of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if loop_closure_rate is None:
            raise ValueError("Invalid value for `loop_closure_rate`, must not be `None`")  # noqa: E501

        self._loop_closure_rate = loop_closure_rate

    @property
    def half_open_rate(self):
        """Gets the half_open_rate of this HostLoopClosure.  # noqa: E501


        :return: The half_open_rate of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._half_open_rate

    @half_open_rate.setter
    def half_open_rate(self, half_open_rate):
        """Sets the half_open_rate of this HostLoopClosure.


        :param half_open_rate: The half_open_rate of this HostLoopClosure.  # noqa: E501
        :type: object
        """
        if half_open_rate is None:
            raise ValueError("Invalid value for `half_open_rate`, must not be `None`")  # noqa: E501

        self._half_open_rate = half_open_rate

    @property
    def avg_seconds_to_close(self):
        """Gets the avg_seconds_to_close of this HostLoopClosure.  # noqa: E501


        :return: The avg_seconds_to_close of this HostLoopClosure.  # noqa: E501
        :rtype: object
        """
        return self._avg_seconds_to_close

    @avg_seconds_to_close.setter
    def avg_seconds_to_close(self, avg_seconds_to_close):
        """Sets the avg_seconds_to_close of this HostLoopClosure.


        :param avg_seconds_to_close: The avg_seconds_to_close of this HostLoopClosure.  # noqa: E501
        :type: object
        """

        self._avg_seconds_to_close = avg_seconds_to_close

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HostLoopClosure, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HostLoopClosure):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
