# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LearningAuditPartialFailure(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'detail': 'object',
        'source': 'object'
    }

    attribute_map = {
        'detail': 'detail',
        'source': 'source'
    }

    def __init__(self, detail=None, source=None):  # noqa: E501
        """LearningAuditPartialFailure - a model defined in Swagger"""  # noqa: E501
        self._detail = None
        self._source = None
        self.discriminator = None
        self.detail = detail
        self.source = source

    @property
    def detail(self):
        """Gets the detail of this LearningAuditPartialFailure.  # noqa: E501

        What was unavailable and the impact.  # noqa: E501

        :return: The detail of this LearningAuditPartialFailure.  # noqa: E501
        :rtype: object
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this LearningAuditPartialFailure.

        What was unavailable and the impact.  # noqa: E501

        :param detail: The detail of this LearningAuditPartialFailure.  # noqa: E501
        :type: object
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")  # noqa: E501

        self._detail = detail

    @property
    def source(self):
        """Gets the source of this LearningAuditPartialFailure.  # noqa: E501

        Stable name of the unavailable data source.  # noqa: E501

        :return: The source of this LearningAuditPartialFailure.  # noqa: E501
        :rtype: object
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this LearningAuditPartialFailure.

        Stable name of the unavailable data source.  # noqa: E501

        :param source: The source of this LearningAuditPartialFailure.  # noqa: E501
        :type: object
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LearningAuditPartialFailure, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LearningAuditPartialFailure):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
