# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MembershipModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tenant_id': 'object',
        'tenant_name': 'object',
        'role': 'object',
        'status': 'object'
    }

    attribute_map = {
        'tenant_id': 'tenantId',
        'tenant_name': 'tenantName',
        'role': 'role',
        'status': 'status'
    }

    def __init__(self, tenant_id=None, tenant_name=None, role=None, status=None):  # noqa: E501
        """MembershipModel - a model defined in Swagger"""  # noqa: E501
        self._tenant_id = None
        self._tenant_name = None
        self._role = None
        self._status = None
        self.discriminator = None
        self.tenant_id = tenant_id
        self.tenant_name = tenant_name
        self.role = role
        self.status = status

    @property
    def tenant_id(self):
        """Gets the tenant_id of this MembershipModel.  # noqa: E501


        :return: The tenant_id of this MembershipModel.  # noqa: E501
        :rtype: object
        """
        return self._tenant_id

    @tenant_id.setter
    def tenant_id(self, tenant_id):
        """Sets the tenant_id of this MembershipModel.


        :param tenant_id: The tenant_id of this MembershipModel.  # noqa: E501
        :type: object
        """
        if tenant_id is None:
            raise ValueError("Invalid value for `tenant_id`, must not be `None`")  # noqa: E501

        self._tenant_id = tenant_id

    @property
    def tenant_name(self):
        """Gets the tenant_name of this MembershipModel.  # noqa: E501


        :return: The tenant_name of this MembershipModel.  # noqa: E501
        :rtype: object
        """
        return self._tenant_name

    @tenant_name.setter
    def tenant_name(self, tenant_name):
        """Sets the tenant_name of this MembershipModel.


        :param tenant_name: The tenant_name of this MembershipModel.  # noqa: E501
        :type: object
        """
        if tenant_name is None:
            raise ValueError("Invalid value for `tenant_name`, must not be `None`")  # noqa: E501

        self._tenant_name = tenant_name

    @property
    def role(self):
        """Gets the role of this MembershipModel.  # noqa: E501


        :return: The role of this MembershipModel.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this MembershipModel.


        :param role: The role of this MembershipModel.  # noqa: E501
        :type: object
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def status(self):
        """Gets the status of this MembershipModel.  # noqa: E501


        :return: The status of this MembershipModel.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MembershipModel.


        :param status: The status of this MembershipModel.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MembershipModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MembershipModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
