# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NormReviewContext(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'object',
        'dormant_until': 'object',
        'etag': 'object',
        'is_retired': 'object',
        'learning_id': 'object',
        'proposed_breaches': 'object',
        'run_digest': 'object',
        'state': 'object',
        'stated_at': 'object',
        'times_applied': 'object',
        'times_offered': 'object'
    }

    attribute_map = {
        'content': 'content',
        'dormant_until': 'dormant_until',
        'etag': 'etag',
        'is_retired': 'is_retired',
        'learning_id': 'learning_id',
        'proposed_breaches': 'proposed_breaches',
        'run_digest': 'run_digest',
        'state': 'state',
        'stated_at': 'stated_at',
        'times_applied': 'times_applied',
        'times_offered': 'times_offered'
    }

    def __init__(self, content=None, dormant_until=None, etag=None, is_retired=None, learning_id=None, proposed_breaches=None, run_digest=None, state=None, stated_at=None, times_applied=None, times_offered=None):  # noqa: E501
        """NormReviewContext - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._dormant_until = None
        self._etag = None
        self._is_retired = None
        self._learning_id = None
        self._proposed_breaches = None
        self._run_digest = None
        self._state = None
        self._stated_at = None
        self._times_applied = None
        self._times_offered = None
        self.discriminator = None
        self.content = content
        if dormant_until is not None:
            self.dormant_until = dormant_until
        self.etag = etag
        self.is_retired = is_retired
        self.learning_id = learning_id
        self.proposed_breaches = proposed_breaches
        self.run_digest = run_digest
        self.state = state
        self.stated_at = stated_at
        self.times_applied = times_applied
        self.times_offered = times_offered

    @property
    def content(self):
        """Gets the content of this NormReviewContext.  # noqa: E501

        The directive as the principal stated it. Typically within 8000 characters; not validated, because Core promises no length and a longer one must still be readable in order to be retired.  # noqa: E501

        :return: The content of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this NormReviewContext.

        The directive as the principal stated it. Typically within 8000 characters; not validated, because Core promises no length and a longer one must still be readable in order to be retired.  # noqa: E501

        :param content: The content of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def dormant_until(self):
        """Gets the dormant_until of this NormReviewContext.  # noqa: E501

        Date this norm is silenced until, or empty when it is not dormant.  # noqa: E501

        :return: The dormant_until of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._dormant_until

    @dormant_until.setter
    def dormant_until(self, dormant_until):
        """Sets the dormant_until of this NormReviewContext.

        Date this norm is silenced until, or empty when it is not dormant.  # noqa: E501

        :param dormant_until: The dormant_until of this NormReviewContext.  # noqa: E501
        :type: object
        """

        self._dormant_until = dormant_until

    @property
    def etag(self):
        """Gets the etag of this NormReviewContext.  # noqa: E501


        :return: The etag of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._etag

    @etag.setter
    def etag(self, etag):
        """Sets the etag of this NormReviewContext.


        :param etag: The etag of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if etag is None:
            raise ValueError("Invalid value for `etag`, must not be `None`")  # noqa: E501

        self._etag = etag

    @property
    def is_retired(self):
        """Gets the is_retired of this NormReviewContext.  # noqa: E501

        Archived by a curator or superseded by a later directive.  # noqa: E501

        :return: The is_retired of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._is_retired

    @is_retired.setter
    def is_retired(self, is_retired):
        """Sets the is_retired of this NormReviewContext.

        Archived by a curator or superseded by a later directive.  # noqa: E501

        :param is_retired: The is_retired of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if is_retired is None:
            raise ValueError("Invalid value for `is_retired`, must not be `None`")  # noqa: E501

        self._is_retired = is_retired

    @property
    def learning_id(self):
        """Gets the learning_id of this NormReviewContext.  # noqa: E501


        :return: The learning_id of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._learning_id

    @learning_id.setter
    def learning_id(self, learning_id):
        """Sets the learning_id of this NormReviewContext.


        :param learning_id: The learning_id of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if learning_id is None:
            raise ValueError("Invalid value for `learning_id`, must not be `None`")  # noqa: E501

        self._learning_id = learning_id

    @property
    def proposed_breaches(self):
        """Gets the proposed_breaches of this NormReviewContext.  # noqa: E501

        Times the critic proposed that a run breached this norm.  # noqa: E501

        :return: The proposed_breaches of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._proposed_breaches

    @proposed_breaches.setter
    def proposed_breaches(self, proposed_breaches):
        """Sets the proposed_breaches of this NormReviewContext.

        Times the critic proposed that a run breached this norm.  # noqa: E501

        :param proposed_breaches: The proposed_breaches of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if proposed_breaches is None:
            raise ValueError("Invalid value for `proposed_breaches`, must not be `None`")  # noqa: E501

        self._proposed_breaches = proposed_breaches

    @property
    def run_digest(self):
        """Gets the run_digest of this NormReviewContext.  # noqa: E501

        Short prefix of the commitment to the run the norm was stated on, so a curator can tell two norms from one session apart. Empty when the record predates the commitment.  # noqa: E501

        :return: The run_digest of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._run_digest

    @run_digest.setter
    def run_digest(self, run_digest):
        """Sets the run_digest of this NormReviewContext.

        Short prefix of the commitment to the run the norm was stated on, so a curator can tell two norms from one session apart. Empty when the record predates the commitment.  # noqa: E501

        :param run_digest: The run_digest of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if run_digest is None:
            raise ValueError("Invalid value for `run_digest`, must not be `None`")  # noqa: E501

        self._run_digest = run_digest

    @property
    def state(self):
        """Gets the state of this NormReviewContext.  # noqa: E501

        Core's lifecycle state for this norm: probation, confirmed or superseded. A norm stated before the lifecycle existed reads as confirmed, because it already had primacy and keeps it.  # noqa: E501

        :return: The state of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this NormReviewContext.

        Core's lifecycle state for this norm: probation, confirmed or superseded. A norm stated before the lifecycle existed reads as confirmed, because it already had primacy and keeps it.  # noqa: E501

        :param state: The state of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def stated_at(self):
        """Gets the stated_at of this NormReviewContext.  # noqa: E501

        The date the principal stated this norm, or 'unknown' for a record written before the date was captured.  # noqa: E501

        :return: The stated_at of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._stated_at

    @stated_at.setter
    def stated_at(self, stated_at):
        """Sets the stated_at of this NormReviewContext.

        The date the principal stated this norm, or 'unknown' for a record written before the date was captured.  # noqa: E501

        :param stated_at: The stated_at of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if stated_at is None:
            raise ValueError("Invalid value for `stated_at`, must not be `None`")  # noqa: E501

        self._stated_at = stated_at

    @property
    def times_applied(self):
        """Gets the times_applied of this NormReviewContext.  # noqa: E501


        :return: The times_applied of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._times_applied

    @times_applied.setter
    def times_applied(self, times_applied):
        """Sets the times_applied of this NormReviewContext.


        :param times_applied: The times_applied of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if times_applied is None:
            raise ValueError("Invalid value for `times_applied`, must not be `None`")  # noqa: E501

        self._times_applied = times_applied

    @property
    def times_offered(self):
        """Gets the times_offered of this NormReviewContext.  # noqa: E501


        :return: The times_offered of this NormReviewContext.  # noqa: E501
        :rtype: object
        """
        return self._times_offered

    @times_offered.setter
    def times_offered(self, times_offered):
        """Sets the times_offered of this NormReviewContext.


        :param times_offered: The times_offered of this NormReviewContext.  # noqa: E501
        :type: object
        """
        if times_offered is None:
            raise ValueError("Invalid value for `times_offered`, must not be `None`")  # noqa: E501

        self._times_offered = times_offered

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NormReviewContext, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NormReviewContext):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
