# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ObligationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_id': 'object',
        'closed_at': 'object',
        'committed_at': 'object',
        'created_at': 'object',
        'dedupe_key': 'object',
        'delivered_count': 'object',
        'dropped_reason': 'object',
        'due_at': 'object',
        'due_from_claim_id': 'object',
        'due_local': 'object',
        'due_precision': 'object',
        'due_tz': 'object',
        'due_tz_basis': 'object',
        'expired_reason': 'object',
        'expires_at': 'object',
        'id': 'object',
        'kept_basis': 'object',
        'kind': 'object',
        'last_surfaced_at': 'object',
        'later_standing': 'object',
        'later_standing_at': 'object',
        'lead_days': 'object',
        'neglect_flagged_at': 'object',
        'not_before': 'object',
        'note': 'object',
        'org_id': 'object',
        'owed_by_entity_id': 'object',
        'owed_by_name': 'object',
        'owed_by_role': 'object',
        'owed_to_entity_id': 'object',
        'owed_to_name': 'object',
        'owed_to_role': 'object',
        'participants': 'object',
        'premise_claim_ids': 'object',
        'privacy': 'object',
        'provenance': 'object',
        'provenance_class': 'object',
        'review_reasons': 'object',
        'statement': 'object',
        'status': 'object',
        'subject_entity_id': 'object',
        'subject_name': 'object',
        'superseded_by': 'object',
        'suppression_until': 'object',
        'surfaced_count': 'object',
        'trigger_kind': 'object',
        'updated_at': 'object',
        'version': 'object'
    }

    attribute_map = {
        'agent_id': 'agent_id',
        'closed_at': 'closed_at',
        'committed_at': 'committed_at',
        'created_at': 'created_at',
        'dedupe_key': 'dedupe_key',
        'delivered_count': 'delivered_count',
        'dropped_reason': 'dropped_reason',
        'due_at': 'due_at',
        'due_from_claim_id': 'due_from_claim_id',
        'due_local': 'due_local',
        'due_precision': 'due_precision',
        'due_tz': 'due_tz',
        'due_tz_basis': 'due_tz_basis',
        'expired_reason': 'expired_reason',
        'expires_at': 'expires_at',
        'id': 'id',
        'kept_basis': 'kept_basis',
        'kind': 'kind',
        'last_surfaced_at': 'last_surfaced_at',
        'later_standing': 'later_standing',
        'later_standing_at': 'later_standing_at',
        'lead_days': 'lead_days',
        'neglect_flagged_at': 'neglect_flagged_at',
        'not_before': 'not_before',
        'note': 'note',
        'org_id': 'org_id',
        'owed_by_entity_id': 'owed_by_entity_id',
        'owed_by_name': 'owed_by_name',
        'owed_by_role': 'owed_by_role',
        'owed_to_entity_id': 'owed_to_entity_id',
        'owed_to_name': 'owed_to_name',
        'owed_to_role': 'owed_to_role',
        'participants': 'participants',
        'premise_claim_ids': 'premise_claim_ids',
        'privacy': 'privacy',
        'provenance': 'provenance',
        'provenance_class': 'provenance_class',
        'review_reasons': 'review_reasons',
        'statement': 'statement',
        'status': 'status',
        'subject_entity_id': 'subject_entity_id',
        'subject_name': 'subject_name',
        'superseded_by': 'superseded_by',
        'suppression_until': 'suppression_until',
        'surfaced_count': 'surfaced_count',
        'trigger_kind': 'trigger_kind',
        'updated_at': 'updated_at',
        'version': 'version'
    }

    def __init__(self, agent_id=None, closed_at=None, committed_at=None, created_at=None, dedupe_key=None, delivered_count=None, dropped_reason=None, due_at=None, due_from_claim_id=None, due_local=None, due_precision=None, due_tz=None, due_tz_basis=None, expired_reason=None, expires_at=None, id=None, kept_basis=None, kind=None, last_surfaced_at=None, later_standing=None, later_standing_at=None, lead_days=None, neglect_flagged_at=None, not_before=None, note=None, org_id=None, owed_by_entity_id=None, owed_by_name=None, owed_by_role=None, owed_to_entity_id=None, owed_to_name=None, owed_to_role=None, participants=None, premise_claim_ids=None, privacy=None, provenance=None, provenance_class=None, review_reasons=None, statement=None, status=None, subject_entity_id=None, subject_name=None, superseded_by=None, suppression_until=None, surfaced_count=None, trigger_kind=None, updated_at=None, version=None):  # noqa: E501
        """ObligationResponse - a model defined in Swagger"""  # noqa: E501
        self._agent_id = None
        self._closed_at = None
        self._committed_at = None
        self._created_at = None
        self._dedupe_key = None
        self._delivered_count = None
        self._dropped_reason = None
        self._due_at = None
        self._due_from_claim_id = None
        self._due_local = None
        self._due_precision = None
        self._due_tz = None
        self._due_tz_basis = None
        self._expired_reason = None
        self._expires_at = None
        self._id = None
        self._kept_basis = None
        self._kind = None
        self._last_surfaced_at = None
        self._later_standing = None
        self._later_standing_at = None
        self._lead_days = None
        self._neglect_flagged_at = None
        self._not_before = None
        self._note = None
        self._org_id = None
        self._owed_by_entity_id = None
        self._owed_by_name = None
        self._owed_by_role = None
        self._owed_to_entity_id = None
        self._owed_to_name = None
        self._owed_to_role = None
        self._participants = None
        self._premise_claim_ids = None
        self._privacy = None
        self._provenance = None
        self._provenance_class = None
        self._review_reasons = None
        self._statement = None
        self._status = None
        self._subject_entity_id = None
        self._subject_name = None
        self._superseded_by = None
        self._suppression_until = None
        self._surfaced_count = None
        self._trigger_kind = None
        self._updated_at = None
        self._version = None
        self.discriminator = None
        self.agent_id = agent_id
        self.closed_at = closed_at
        self.committed_at = committed_at
        self.created_at = created_at
        self.dedupe_key = dedupe_key
        self.delivered_count = delivered_count
        self.dropped_reason = dropped_reason
        self.due_at = due_at
        self.due_from_claim_id = due_from_claim_id
        if due_local is not None:
            self.due_local = due_local
        self.due_precision = due_precision
        self.due_tz = due_tz
        if due_tz_basis is not None:
            self.due_tz_basis = due_tz_basis
        self.expired_reason = expired_reason
        self.expires_at = expires_at
        self.id = id
        self.kept_basis = kept_basis
        if kind is not None:
            self.kind = kind
        self.last_surfaced_at = last_surfaced_at
        if later_standing is not None:
            self.later_standing = later_standing
        if later_standing_at is not None:
            self.later_standing_at = later_standing_at
        self.lead_days = lead_days
        self.neglect_flagged_at = neglect_flagged_at
        self.not_before = not_before
        if note is not None:
            self.note = note
        self.org_id = org_id
        self.owed_by_entity_id = owed_by_entity_id
        if owed_by_name is not None:
            self.owed_by_name = owed_by_name
        self.owed_by_role = owed_by_role
        self.owed_to_entity_id = owed_to_entity_id
        if owed_to_name is not None:
            self.owed_to_name = owed_to_name
        self.owed_to_role = owed_to_role
        if participants is not None:
            self.participants = participants
        self.premise_claim_ids = premise_claim_ids
        self.privacy = privacy
        self.provenance = provenance
        self.provenance_class = provenance_class
        if review_reasons is not None:
            self.review_reasons = review_reasons
        self.statement = statement
        self.status = status
        self.subject_entity_id = subject_entity_id
        if subject_name is not None:
            self.subject_name = subject_name
        self.superseded_by = superseded_by
        self.suppression_until = suppression_until
        self.surfaced_count = surfaced_count
        self.trigger_kind = trigger_kind
        self.updated_at = updated_at
        self.version = version

    @property
    def agent_id(self):
        """Gets the agent_id of this ObligationResponse.  # noqa: E501


        :return: The agent_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this ObligationResponse.


        :param agent_id: The agent_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if agent_id is None:
            raise ValueError("Invalid value for `agent_id`, must not be `None`")  # noqa: E501

        self._agent_id = agent_id

    @property
    def closed_at(self):
        """Gets the closed_at of this ObligationResponse.  # noqa: E501


        :return: The closed_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._closed_at

    @closed_at.setter
    def closed_at(self, closed_at):
        """Sets the closed_at of this ObligationResponse.


        :param closed_at: The closed_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if closed_at is None:
            raise ValueError("Invalid value for `closed_at`, must not be `None`")  # noqa: E501

        self._closed_at = closed_at

    @property
    def committed_at(self):
        """Gets the committed_at of this ObligationResponse.  # noqa: E501


        :return: The committed_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._committed_at

    @committed_at.setter
    def committed_at(self, committed_at):
        """Sets the committed_at of this ObligationResponse.


        :param committed_at: The committed_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if committed_at is None:
            raise ValueError("Invalid value for `committed_at`, must not be `None`")  # noqa: E501

        self._committed_at = committed_at

    @property
    def created_at(self):
        """Gets the created_at of this ObligationResponse.  # noqa: E501


        :return: The created_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ObligationResponse.


        :param created_at: The created_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def dedupe_key(self):
        """Gets the dedupe_key of this ObligationResponse.  # noqa: E501


        :return: The dedupe_key of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._dedupe_key

    @dedupe_key.setter
    def dedupe_key(self, dedupe_key):
        """Sets the dedupe_key of this ObligationResponse.


        :param dedupe_key: The dedupe_key of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if dedupe_key is None:
            raise ValueError("Invalid value for `dedupe_key`, must not be `None`")  # noqa: E501

        self._dedupe_key = dedupe_key

    @property
    def delivered_count(self):
        """Gets the delivered_count of this ObligationResponse.  # noqa: E501


        :return: The delivered_count of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._delivered_count

    @delivered_count.setter
    def delivered_count(self, delivered_count):
        """Sets the delivered_count of this ObligationResponse.


        :param delivered_count: The delivered_count of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if delivered_count is None:
            raise ValueError("Invalid value for `delivered_count`, must not be `None`")  # noqa: E501

        self._delivered_count = delivered_count

    @property
    def dropped_reason(self):
        """Gets the dropped_reason of this ObligationResponse.  # noqa: E501


        :return: The dropped_reason of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._dropped_reason

    @dropped_reason.setter
    def dropped_reason(self, dropped_reason):
        """Sets the dropped_reason of this ObligationResponse.


        :param dropped_reason: The dropped_reason of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if dropped_reason is None:
            raise ValueError("Invalid value for `dropped_reason`, must not be `None`")  # noqa: E501

        self._dropped_reason = dropped_reason

    @property
    def due_at(self):
        """Gets the due_at of this ObligationResponse.  # noqa: E501

        The first instant the obligation is overdue. When due_precision is 'date', that is the start of the day after due_local in due_tz, one day ahead of the day that was meant. Returned as stored, not converted: render due_local instead.  # noqa: E501

        :return: The due_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_at

    @due_at.setter
    def due_at(self, due_at):
        """Sets the due_at of this ObligationResponse.

        The first instant the obligation is overdue. When due_precision is 'date', that is the start of the day after due_local in due_tz, one day ahead of the day that was meant. Returned as stored, not converted: render due_local instead.  # noqa: E501

        :param due_at: The due_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if due_at is None:
            raise ValueError("Invalid value for `due_at`, must not be `None`")  # noqa: E501

        self._due_at = due_at

    @property
    def due_from_claim_id(self):
        """Gets the due_from_claim_id of this ObligationResponse.  # noqa: E501


        :return: The due_from_claim_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_from_claim_id

    @due_from_claim_id.setter
    def due_from_claim_id(self, due_from_claim_id):
        """Sets the due_from_claim_id of this ObligationResponse.


        :param due_from_claim_id: The due_from_claim_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if due_from_claim_id is None:
            raise ValueError("Invalid value for `due_from_claim_id`, must not be `None`")  # noqa: E501

        self._due_from_claim_id = due_from_claim_id

    @property
    def due_local(self):
        """Gets the due_local of this ObligationResponse.  # noqa: E501

        due_at rendered for the caller. When due_precision is 'date', this is the due DAY as 'YYYY-MM-DD' in the due's own zone. When due_precision is 'datetime', this is the ISO instant converted into the requested (or agent default) zone.  # noqa: E501

        :return: The due_local of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_local

    @due_local.setter
    def due_local(self, due_local):
        """Sets the due_local of this ObligationResponse.

        due_at rendered for the caller. When due_precision is 'date', this is the due DAY as 'YYYY-MM-DD' in the due's own zone. When due_precision is 'datetime', this is the ISO instant converted into the requested (or agent default) zone.  # noqa: E501

        :param due_local: The due_local of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._due_local = due_local

    @property
    def due_precision(self):
        """Gets the due_precision of this ObligationResponse.  # noqa: E501


        :return: The due_precision of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_precision

    @due_precision.setter
    def due_precision(self, due_precision):
        """Sets the due_precision of this ObligationResponse.


        :param due_precision: The due_precision of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if due_precision is None:
            raise ValueError("Invalid value for `due_precision`, must not be `None`")  # noqa: E501

        self._due_precision = due_precision

    @property
    def due_tz(self):
        """Gets the due_tz of this ObligationResponse.  # noqa: E501

        The due's own zone: an IANA zone or, when that is all the source gave, a fixed offset.  # noqa: E501

        :return: The due_tz of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_tz

    @due_tz.setter
    def due_tz(self, due_tz):
        """Sets the due_tz of this ObligationResponse.

        The due's own zone: an IANA zone or, when that is all the source gave, a fixed offset.  # noqa: E501

        :param due_tz: The due_tz of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if due_tz is None:
            raise ValueError("Invalid value for `due_tz`, must not be `None`")  # noqa: E501

        self._due_tz = due_tz

    @property
    def due_tz_basis(self):
        """Gets the due_tz_basis of this ObligationResponse.  # noqa: E501

        Where due_tz came from: 'phrase' (the due phrase named a zone), 'note' (the note declared one), 'agent' (the agent's default), 'offset' (the note's timestamp offset), 'caller' (a person set the due), or 'defaulted' (nothing said, UTC was assumed). Null on rows written before it was recorded. A 'defaulted' due's day may be wrong.  # noqa: E501

        :return: The due_tz_basis of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._due_tz_basis

    @due_tz_basis.setter
    def due_tz_basis(self, due_tz_basis):
        """Sets the due_tz_basis of this ObligationResponse.

        Where due_tz came from: 'phrase' (the due phrase named a zone), 'note' (the note declared one), 'agent' (the agent's default), 'offset' (the note's timestamp offset), 'caller' (a person set the due), or 'defaulted' (nothing said, UTC was assumed). Null on rows written before it was recorded. A 'defaulted' due's day may be wrong.  # noqa: E501

        :param due_tz_basis: The due_tz_basis of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._due_tz_basis = due_tz_basis

    @property
    def expired_reason(self):
        """Gets the expired_reason of this ObligationResponse.  # noqa: E501


        :return: The expired_reason of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._expired_reason

    @expired_reason.setter
    def expired_reason(self, expired_reason):
        """Sets the expired_reason of this ObligationResponse.


        :param expired_reason: The expired_reason of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if expired_reason is None:
            raise ValueError("Invalid value for `expired_reason`, must not be `None`")  # noqa: E501

        self._expired_reason = expired_reason

    @property
    def expires_at(self):
        """Gets the expires_at of this ObligationResponse.  # noqa: E501


        :return: The expires_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._expires_at

    @expires_at.setter
    def expires_at(self, expires_at):
        """Sets the expires_at of this ObligationResponse.


        :param expires_at: The expires_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if expires_at is None:
            raise ValueError("Invalid value for `expires_at`, must not be `None`")  # noqa: E501

        self._expires_at = expires_at

    @property
    def id(self):
        """Gets the id of this ObligationResponse.  # noqa: E501


        :return: The id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ObligationResponse.


        :param id: The id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def kept_basis(self):
        """Gets the kept_basis of this ObligationResponse.  # noqa: E501


        :return: The kept_basis of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._kept_basis

    @kept_basis.setter
    def kept_basis(self, kept_basis):
        """Sets the kept_basis of this ObligationResponse.


        :param kept_basis: The kept_basis of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if kept_basis is None:
            raise ValueError("Invalid value for `kept_basis`, must not be `None`")  # noqa: E501

        self._kept_basis = kept_basis

    @property
    def kind(self):
        """Gets the kind of this ObligationResponse.  # noqa: E501

        A commitment one party owes, or a meeting owed jointly by its attendees.  # noqa: E501

        :return: The kind of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this ObligationResponse.

        A commitment one party owes, or a meeting owed jointly by its attendees.  # noqa: E501

        :param kind: The kind of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._kind = kind

    @property
    def last_surfaced_at(self):
        """Gets the last_surfaced_at of this ObligationResponse.  # noqa: E501


        :return: The last_surfaced_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._last_surfaced_at

    @last_surfaced_at.setter
    def last_surfaced_at(self, last_surfaced_at):
        """Sets the last_surfaced_at of this ObligationResponse.


        :param last_surfaced_at: The last_surfaced_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if last_surfaced_at is None:
            raise ValueError("Invalid value for `last_surfaced_at`, must not be `None`")  # noqa: E501

        self._last_surfaced_at = last_surfaced_at

    @property
    def later_standing(self):
        """Gets the later_standing of this ObligationResponse.  # noqa: E501

        What a LATER note said about this obligation: its kind (already_done, withdrawn or superseded), and the phrase and corpus span it was read from. The row stays open; the flag is a question for a person, never an outcome.  # noqa: E501

        :return: The later_standing of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._later_standing

    @later_standing.setter
    def later_standing(self, later_standing):
        """Sets the later_standing of this ObligationResponse.

        What a LATER note said about this obligation: its kind (already_done, withdrawn or superseded), and the phrase and corpus span it was read from. The row stays open; the flag is a question for a person, never an outcome.  # noqa: E501

        :param later_standing: The later_standing of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._later_standing = later_standing

    @property
    def later_standing_at(self):
        """Gets the later_standing_at of this ObligationResponse.  # noqa: E501


        :return: The later_standing_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._later_standing_at

    @later_standing_at.setter
    def later_standing_at(self, later_standing_at):
        """Sets the later_standing_at of this ObligationResponse.


        :param later_standing_at: The later_standing_at of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._later_standing_at = later_standing_at

    @property
    def lead_days(self):
        """Gets the lead_days of this ObligationResponse.  # noqa: E501


        :return: The lead_days of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._lead_days

    @lead_days.setter
    def lead_days(self, lead_days):
        """Sets the lead_days of this ObligationResponse.


        :param lead_days: The lead_days of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if lead_days is None:
            raise ValueError("Invalid value for `lead_days`, must not be `None`")  # noqa: E501

        self._lead_days = lead_days

    @property
    def neglect_flagged_at(self):
        """Gets the neglect_flagged_at of this ObligationResponse.  # noqa: E501


        :return: The neglect_flagged_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._neglect_flagged_at

    @neglect_flagged_at.setter
    def neglect_flagged_at(self, neglect_flagged_at):
        """Sets the neglect_flagged_at of this ObligationResponse.


        :param neglect_flagged_at: The neglect_flagged_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if neglect_flagged_at is None:
            raise ValueError("Invalid value for `neglect_flagged_at`, must not be `None`")  # noqa: E501

        self._neglect_flagged_at = neglect_flagged_at

    @property
    def not_before(self):
        """Gets the not_before of this ObligationResponse.  # noqa: E501


        :return: The not_before of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._not_before

    @not_before.setter
    def not_before(self, not_before):
        """Sets the not_before of this ObligationResponse.


        :param not_before: The not_before of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if not_before is None:
            raise ValueError("Invalid value for `not_before`, must not be `None`")  # noqa: E501

        self._not_before = not_before

    @property
    def note(self):
        """Gets the note of this ObligationResponse.  # noqa: E501

        Only on a single-obligation read, and only for a line harvested from a stored note. Null for every other line and on every list.  # noqa: E501

        :return: The note of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this ObligationResponse.

        Only on a single-obligation read, and only for a line harvested from a stored note. Null for every other line and on every list.  # noqa: E501

        :param note: The note of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._note = note

    @property
    def org_id(self):
        """Gets the org_id of this ObligationResponse.  # noqa: E501


        :return: The org_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this ObligationResponse.


        :param org_id: The org_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if org_id is None:
            raise ValueError("Invalid value for `org_id`, must not be `None`")  # noqa: E501

        self._org_id = org_id

    @property
    def owed_by_entity_id(self):
        """Gets the owed_by_entity_id of this ObligationResponse.  # noqa: E501


        :return: The owed_by_entity_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_by_entity_id

    @owed_by_entity_id.setter
    def owed_by_entity_id(self, owed_by_entity_id):
        """Sets the owed_by_entity_id of this ObligationResponse.


        :param owed_by_entity_id: The owed_by_entity_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if owed_by_entity_id is None:
            raise ValueError("Invalid value for `owed_by_entity_id`, must not be `None`")  # noqa: E501

        self._owed_by_entity_id = owed_by_entity_id

    @property
    def owed_by_name(self):
        """Gets the owed_by_name of this ObligationResponse.  # noqa: E501

        The obligor's canonical name, resolved from the registry at read time rather than copied onto the obligation, so an entity merge or an erasure is honoured by the next read. Null when the party is a bare role, or when the name does not resolve for this caller.  # noqa: E501

        :return: The owed_by_name of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_by_name

    @owed_by_name.setter
    def owed_by_name(self, owed_by_name):
        """Sets the owed_by_name of this ObligationResponse.

        The obligor's canonical name, resolved from the registry at read time rather than copied onto the obligation, so an entity merge or an erasure is honoured by the next read. Null when the party is a bare role, or when the name does not resolve for this caller.  # noqa: E501

        :param owed_by_name: The owed_by_name of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._owed_by_name = owed_by_name

    @property
    def owed_by_role(self):
        """Gets the owed_by_role of this ObligationResponse.  # noqa: E501


        :return: The owed_by_role of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_by_role

    @owed_by_role.setter
    def owed_by_role(self, owed_by_role):
        """Sets the owed_by_role of this ObligationResponse.


        :param owed_by_role: The owed_by_role of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if owed_by_role is None:
            raise ValueError("Invalid value for `owed_by_role`, must not be `None`")  # noqa: E501

        self._owed_by_role = owed_by_role

    @property
    def owed_to_entity_id(self):
        """Gets the owed_to_entity_id of this ObligationResponse.  # noqa: E501


        :return: The owed_to_entity_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_to_entity_id

    @owed_to_entity_id.setter
    def owed_to_entity_id(self, owed_to_entity_id):
        """Sets the owed_to_entity_id of this ObligationResponse.


        :param owed_to_entity_id: The owed_to_entity_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if owed_to_entity_id is None:
            raise ValueError("Invalid value for `owed_to_entity_id`, must not be `None`")  # noqa: E501

        self._owed_to_entity_id = owed_to_entity_id

    @property
    def owed_to_name(self):
        """Gets the owed_to_name of this ObligationResponse.  # noqa: E501

        The obligee's canonical name, resolved the same way as owed_by_name. On the corpus-harvested lane this is who the commitment was made to, and without it a curation surface can only show an opaque id.  # noqa: E501

        :return: The owed_to_name of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_to_name

    @owed_to_name.setter
    def owed_to_name(self, owed_to_name):
        """Sets the owed_to_name of this ObligationResponse.

        The obligee's canonical name, resolved the same way as owed_by_name. On the corpus-harvested lane this is who the commitment was made to, and without it a curation surface can only show an opaque id.  # noqa: E501

        :param owed_to_name: The owed_to_name of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._owed_to_name = owed_to_name

    @property
    def owed_to_role(self):
        """Gets the owed_to_role of this ObligationResponse.  # noqa: E501


        :return: The owed_to_role of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._owed_to_role

    @owed_to_role.setter
    def owed_to_role(self, owed_to_role):
        """Sets the owed_to_role of this ObligationResponse.


        :param owed_to_role: The owed_to_role of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if owed_to_role is None:
            raise ValueError("Invalid value for `owed_to_role`, must not be `None`")  # noqa: E501

        self._owed_to_role = owed_to_role

    @property
    def participants(self):
        """Gets the participants of this ObligationResponse.  # noqa: E501

        Everyone on the obligation when a party was a list: \"Brad and Daniel\" is owed_by Brad with both Brad and Daniel here as owners. Empty when each side names one party.  # noqa: E501

        :return: The participants of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._participants

    @participants.setter
    def participants(self, participants):
        """Sets the participants of this ObligationResponse.

        Everyone on the obligation when a party was a list: \"Brad and Daniel\" is owed_by Brad with both Brad and Daniel here as owners. Empty when each side names one party.  # noqa: E501

        :param participants: The participants of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._participants = participants

    @property
    def premise_claim_ids(self):
        """Gets the premise_claim_ids of this ObligationResponse.  # noqa: E501


        :return: The premise_claim_ids of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._premise_claim_ids

    @premise_claim_ids.setter
    def premise_claim_ids(self, premise_claim_ids):
        """Sets the premise_claim_ids of this ObligationResponse.


        :param premise_claim_ids: The premise_claim_ids of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if premise_claim_ids is None:
            raise ValueError("Invalid value for `premise_claim_ids`, must not be `None`")  # noqa: E501

        self._premise_claim_ids = premise_claim_ids

    @property
    def privacy(self):
        """Gets the privacy of this ObligationResponse.  # noqa: E501


        :return: The privacy of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._privacy

    @privacy.setter
    def privacy(self, privacy):
        """Sets the privacy of this ObligationResponse.


        :param privacy: The privacy of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if privacy is None:
            raise ValueError("Invalid value for `privacy`, must not be `None`")  # noqa: E501

        self._privacy = privacy

    @property
    def provenance(self):
        """Gets the provenance of this ObligationResponse.  # noqa: E501


        :return: The provenance of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._provenance

    @provenance.setter
    def provenance(self, provenance):
        """Sets the provenance of this ObligationResponse.


        :param provenance: The provenance of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if provenance is None:
            raise ValueError("Invalid value for `provenance`, must not be `None`")  # noqa: E501

        self._provenance = provenance

    @property
    def provenance_class(self):
        """Gets the provenance_class of this ObligationResponse.  # noqa: E501


        :return: The provenance_class of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._provenance_class

    @provenance_class.setter
    def provenance_class(self, provenance_class):
        """Sets the provenance_class of this ObligationResponse.


        :param provenance_class: The provenance_class of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if provenance_class is None:
            raise ValueError("Invalid value for `provenance_class`, must not be `None`")  # noqa: E501

        self._provenance_class = provenance_class

    @property
    def review_reasons(self):
        """Gets the review_reasons of this ObligationResponse.  # noqa: E501

        Why this obligation is waiting on a person rather than on its due date. Populated only by ?needs_review=true; empty on every other read, which makes no claim either way rather than asserting nothing is wrong. One of untrusted_provenance, premise_retracted, later_standing, neglected; a row may carry several.  # noqa: E501

        :return: The review_reasons of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._review_reasons

    @review_reasons.setter
    def review_reasons(self, review_reasons):
        """Sets the review_reasons of this ObligationResponse.

        Why this obligation is waiting on a person rather than on its due date. Populated only by ?needs_review=true; empty on every other read, which makes no claim either way rather than asserting nothing is wrong. One of untrusted_provenance, premise_retracted, later_standing, neglected; a row may carry several.  # noqa: E501

        :param review_reasons: The review_reasons of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._review_reasons = review_reasons

    @property
    def statement(self):
        """Gets the statement of this ObligationResponse.  # noqa: E501


        :return: The statement of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._statement

    @statement.setter
    def statement(self, statement):
        """Sets the statement of this ObligationResponse.


        :param statement: The statement of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if statement is None:
            raise ValueError("Invalid value for `statement`, must not be `None`")  # noqa: E501

        self._statement = statement

    @property
    def status(self):
        """Gets the status of this ObligationResponse.  # noqa: E501


        :return: The status of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ObligationResponse.


        :param status: The status of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def subject_entity_id(self):
        """Gets the subject_entity_id of this ObligationResponse.  # noqa: E501


        :return: The subject_entity_id of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._subject_entity_id

    @subject_entity_id.setter
    def subject_entity_id(self, subject_entity_id):
        """Sets the subject_entity_id of this ObligationResponse.


        :param subject_entity_id: The subject_entity_id of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if subject_entity_id is None:
            raise ValueError("Invalid value for `subject_entity_id`, must not be `None`")  # noqa: E501

        self._subject_entity_id = subject_entity_id

    @property
    def subject_name(self):
        """Gets the subject_name of this ObligationResponse.  # noqa: E501

        The subject entity's canonical name, resolved from the registry at read time. Null when the obligation names no subject, or when the name does not resolve for this caller.  # noqa: E501

        :return: The subject_name of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._subject_name

    @subject_name.setter
    def subject_name(self, subject_name):
        """Sets the subject_name of this ObligationResponse.

        The subject entity's canonical name, resolved from the registry at read time. Null when the obligation names no subject, or when the name does not resolve for this caller.  # noqa: E501

        :param subject_name: The subject_name of this ObligationResponse.  # noqa: E501
        :type: object
        """

        self._subject_name = subject_name

    @property
    def superseded_by(self):
        """Gets the superseded_by of this ObligationResponse.  # noqa: E501


        :return: The superseded_by of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._superseded_by

    @superseded_by.setter
    def superseded_by(self, superseded_by):
        """Sets the superseded_by of this ObligationResponse.


        :param superseded_by: The superseded_by of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if superseded_by is None:
            raise ValueError("Invalid value for `superseded_by`, must not be `None`")  # noqa: E501

        self._superseded_by = superseded_by

    @property
    def suppression_until(self):
        """Gets the suppression_until of this ObligationResponse.  # noqa: E501


        :return: The suppression_until of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._suppression_until

    @suppression_until.setter
    def suppression_until(self, suppression_until):
        """Sets the suppression_until of this ObligationResponse.


        :param suppression_until: The suppression_until of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if suppression_until is None:
            raise ValueError("Invalid value for `suppression_until`, must not be `None`")  # noqa: E501

        self._suppression_until = suppression_until

    @property
    def surfaced_count(self):
        """Gets the surfaced_count of this ObligationResponse.  # noqa: E501


        :return: The surfaced_count of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._surfaced_count

    @surfaced_count.setter
    def surfaced_count(self, surfaced_count):
        """Sets the surfaced_count of this ObligationResponse.


        :param surfaced_count: The surfaced_count of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if surfaced_count is None:
            raise ValueError("Invalid value for `surfaced_count`, must not be `None`")  # noqa: E501

        self._surfaced_count = surfaced_count

    @property
    def trigger_kind(self):
        """Gets the trigger_kind of this ObligationResponse.  # noqa: E501


        :return: The trigger_kind of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._trigger_kind

    @trigger_kind.setter
    def trigger_kind(self, trigger_kind):
        """Sets the trigger_kind of this ObligationResponse.


        :param trigger_kind: The trigger_kind of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if trigger_kind is None:
            raise ValueError("Invalid value for `trigger_kind`, must not be `None`")  # noqa: E501

        self._trigger_kind = trigger_kind

    @property
    def updated_at(self):
        """Gets the updated_at of this ObligationResponse.  # noqa: E501


        :return: The updated_at of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ObligationResponse.


        :param updated_at: The updated_at of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def version(self):
        """Gets the version of this ObligationResponse.  # noqa: E501


        :return: The version of this ObligationResponse.  # noqa: E501
        :rtype: object
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ObligationResponse.


        :param version: The version of this ObligationResponse.  # noqa: E501
        :type: object
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObligationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObligationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
