# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ObligationDueModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'at': 'object',
        'precision': 'object',
        'tz': 'object'
    }

    attribute_map = {
        'at': 'at',
        'precision': 'precision',
        'tz': 'tz'
    }

    def __init__(self, at=None, precision=None, tz=None):  # noqa: E501
        """ObligationDueModel - a model defined in Swagger"""  # noqa: E501
        self._at = None
        self._precision = None
        self._tz = None
        self.discriminator = None
        self.at = at
        if precision is not None:
            self.precision = precision
        if tz is not None:
            self.tz = tz

    @property
    def at(self):
        """Gets the at of this ObligationDueModel.  # noqa: E501

        The due instant. Naive datetimes are refused, not assumed UTC.  # noqa: E501

        :return: The at of this ObligationDueModel.  # noqa: E501
        :rtype: object
        """
        return self._at

    @at.setter
    def at(self, at):
        """Sets the at of this ObligationDueModel.

        The due instant. Naive datetimes are refused, not assumed UTC.  # noqa: E501

        :param at: The at of this ObligationDueModel.  # noqa: E501
        :type: object
        """
        if at is None:
            raise ValueError("Invalid value for `at`, must not be `None`")  # noqa: E501

        self._at = at

    @property
    def precision(self):
        """Gets the precision of this ObligationDueModel.  # noqa: E501

        'date': overdue at end of day in the zone. 'datetime': overdue at the exact instant.  # noqa: E501

        :return: The precision of this ObligationDueModel.  # noqa: E501
        :rtype: object
        """
        return self._precision

    @precision.setter
    def precision(self, precision):
        """Sets the precision of this ObligationDueModel.

        'date': overdue at end of day in the zone. 'datetime': overdue at the exact instant.  # noqa: E501

        :param precision: The precision of this ObligationDueModel.  # noqa: E501
        :type: object
        """

        self._precision = precision

    @property
    def tz(self):
        """Gets the tz of this ObligationDueModel.  # noqa: E501

        IANA zone name the due was stated in. Defaults to the request timezone, then the agent's, then UTC.  # noqa: E501

        :return: The tz of this ObligationDueModel.  # noqa: E501
        :rtype: object
        """
        return self._tz

    @tz.setter
    def tz(self, tz):
        """Sets the tz of this ObligationDueModel.

        IANA zone name the due was stated in. Defaults to the request timezone, then the agent's, then UTC.  # noqa: E501

        :param tz: The tz of this ObligationDueModel.  # noqa: E501
        :type: object
        """

        self._tz = tz

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ObligationDueModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ObligationDueModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
