# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OrgMemberRoleUpdateResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'identity_user_id': 'object',
        'role': 'object',
        'status': 'object',
        'updated_at': 'object'
    }

    attribute_map = {
        'identity_user_id': 'identity_user_id',
        'role': 'role',
        'status': 'status',
        'updated_at': 'updated_at'
    }

    def __init__(self, identity_user_id=None, role=None, status=None, updated_at=None):  # noqa: E501
        """OrgMemberRoleUpdateResponse - a model defined in Swagger"""  # noqa: E501
        self._identity_user_id = None
        self._role = None
        self._status = None
        self._updated_at = None
        self.discriminator = None
        self.identity_user_id = identity_user_id
        self.role = role
        self.status = status
        self.updated_at = updated_at

    @property
    def identity_user_id(self):
        """Gets the identity_user_id of this OrgMemberRoleUpdateResponse.  # noqa: E501


        :return: The identity_user_id of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :rtype: object
        """
        return self._identity_user_id

    @identity_user_id.setter
    def identity_user_id(self, identity_user_id):
        """Sets the identity_user_id of this OrgMemberRoleUpdateResponse.


        :param identity_user_id: The identity_user_id of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :type: object
        """
        if identity_user_id is None:
            raise ValueError("Invalid value for `identity_user_id`, must not be `None`")  # noqa: E501

        self._identity_user_id = identity_user_id

    @property
    def role(self):
        """Gets the role of this OrgMemberRoleUpdateResponse.  # noqa: E501


        :return: The role of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :rtype: object
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this OrgMemberRoleUpdateResponse.


        :param role: The role of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :type: object
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def status(self):
        """Gets the status of this OrgMemberRoleUpdateResponse.  # noqa: E501


        :return: The status of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrgMemberRoleUpdateResponse.


        :param status: The status of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def updated_at(self):
        """Gets the updated_at of this OrgMemberRoleUpdateResponse.  # noqa: E501


        :return: The updated_at of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this OrgMemberRoleUpdateResponse.


        :param updated_at: The updated_at of this OrgMemberRoleUpdateResponse.  # noqa: E501
        :type: object
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OrgMemberRoleUpdateResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrgMemberRoleUpdateResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
