# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PlanMilestoneResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'object',
        'is_completed': 'object',
        'is_degraded': 'object',
        'milestone_id': 'object',
        'name': 'object',
        'step_ids': 'object'
    }

    attribute_map = {
        'description': 'description',
        'is_completed': 'is_completed',
        'is_degraded': 'is_degraded',
        'milestone_id': 'milestone_id',
        'name': 'name',
        'step_ids': 'step_ids'
    }

    def __init__(self, description=None, is_completed=None, is_degraded=None, milestone_id=None, name=None, step_ids=None):  # noqa: E501
        """PlanMilestoneResponse - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._is_completed = None
        self._is_degraded = None
        self._milestone_id = None
        self._name = None
        self._step_ids = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if is_completed is not None:
            self.is_completed = is_completed
        if is_degraded is not None:
            self.is_degraded = is_degraded
        if milestone_id is not None:
            self.milestone_id = milestone_id
        self.name = name
        if step_ids is not None:
            self.step_ids = step_ids

    @property
    def description(self):
        """Gets the description of this PlanMilestoneResponse.  # noqa: E501


        :return: The description of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PlanMilestoneResponse.


        :param description: The description of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def is_completed(self):
        """Gets the is_completed of this PlanMilestoneResponse.  # noqa: E501


        :return: The is_completed of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._is_completed

    @is_completed.setter
    def is_completed(self, is_completed):
        """Sets the is_completed of this PlanMilestoneResponse.


        :param is_completed: The is_completed of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """

        self._is_completed = is_completed

    @property
    def is_degraded(self):
        """Gets the is_degraded of this PlanMilestoneResponse.  # noqa: E501


        :return: The is_degraded of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._is_degraded

    @is_degraded.setter
    def is_degraded(self, is_degraded):
        """Sets the is_degraded of this PlanMilestoneResponse.


        :param is_degraded: The is_degraded of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """

        self._is_degraded = is_degraded

    @property
    def milestone_id(self):
        """Gets the milestone_id of this PlanMilestoneResponse.  # noqa: E501


        :return: The milestone_id of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._milestone_id

    @milestone_id.setter
    def milestone_id(self, milestone_id):
        """Sets the milestone_id of this PlanMilestoneResponse.


        :param milestone_id: The milestone_id of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """

        self._milestone_id = milestone_id

    @property
    def name(self):
        """Gets the name of this PlanMilestoneResponse.  # noqa: E501


        :return: The name of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlanMilestoneResponse.


        :param name: The name of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def step_ids(self):
        """Gets the step_ids of this PlanMilestoneResponse.  # noqa: E501


        :return: The step_ids of this PlanMilestoneResponse.  # noqa: E501
        :rtype: object
        """
        return self._step_ids

    @step_ids.setter
    def step_ids(self, step_ids):
        """Sets the step_ids of this PlanMilestoneResponse.


        :param step_ids: The step_ids of this PlanMilestoneResponse.  # noqa: E501
        :type: object
        """

        self._step_ids = step_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanMilestoneResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanMilestoneResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
