# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class QuarantineQueueResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'filtered': 'object',
        'items': 'object',
        'next_cursor': 'object',
        'withheld_count': 'object'
    }

    attribute_map = {
        'filtered': 'filtered',
        'items': 'items',
        'next_cursor': 'next_cursor',
        'withheld_count': 'withheld_count'
    }

    def __init__(self, filtered=None, items=None, next_cursor=None, withheld_count=None):  # noqa: E501
        """QuarantineQueueResponse - a model defined in Swagger"""  # noqa: E501
        self._filtered = None
        self._items = None
        self._next_cursor = None
        self._withheld_count = None
        self.discriminator = None
        if filtered is not None:
            self.filtered = filtered
        self.items = items
        if next_cursor is not None:
            self.next_cursor = next_cursor
        if withheld_count is not None:
            self.withheld_count = withheld_count

    @property
    def filtered(self):
        """Gets the filtered of this QuarantineQueueResponse.  # noqa: E501

        True when the caller's readable-space set is restricted and space filtering applied to this page.  # noqa: E501

        :return: The filtered of this QuarantineQueueResponse.  # noqa: E501
        :rtype: object
        """
        return self._filtered

    @filtered.setter
    def filtered(self, filtered):
        """Sets the filtered of this QuarantineQueueResponse.

        True when the caller's readable-space set is restricted and space filtering applied to this page.  # noqa: E501

        :param filtered: The filtered of this QuarantineQueueResponse.  # noqa: E501
        :type: object
        """

        self._filtered = filtered

    @property
    def items(self):
        """Gets the items of this QuarantineQueueResponse.  # noqa: E501


        :return: The items of this QuarantineQueueResponse.  # noqa: E501
        :rtype: object
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this QuarantineQueueResponse.


        :param items: The items of this QuarantineQueueResponse.  # noqa: E501
        :type: object
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    @property
    def next_cursor(self):
        """Gets the next_cursor of this QuarantineQueueResponse.  # noqa: E501


        :return: The next_cursor of this QuarantineQueueResponse.  # noqa: E501
        :rtype: object
        """
        return self._next_cursor

    @next_cursor.setter
    def next_cursor(self, next_cursor):
        """Sets the next_cursor of this QuarantineQueueResponse.


        :param next_cursor: The next_cursor of this QuarantineQueueResponse.  # noqa: E501
        :type: object
        """

        self._next_cursor = next_cursor

    @property
    def withheld_count(self):
        """Gets the withheld_count of this QuarantineQueueResponse.  # noqa: E501

        Best-effort count of rows this page omitted because the caller's space filter excluded them.  # noqa: E501

        :return: The withheld_count of this QuarantineQueueResponse.  # noqa: E501
        :rtype: object
        """
        return self._withheld_count

    @withheld_count.setter
    def withheld_count(self, withheld_count):
        """Sets the withheld_count of this QuarantineQueueResponse.

        Best-effort count of rows this page omitted because the caller's space filter excluded them.  # noqa: E501

        :param withheld_count: The withheld_count of this QuarantineQueueResponse.  # noqa: E501
        :type: object
        """

        self._withheld_count = withheld_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(QuarantineQueueResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuarantineQueueResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
