# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReinforceRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_name': 'object',
        'context_receipt': 'object',
        'episode': 'EpisodeModel',
        'is_delivered': 'object',
        'is_org_promotion_allowed': 'object',
        'org_id': 'object',
        'recall_outcome': 'object'
    }

    attribute_map = {
        'agent_name': 'agent_name',
        'context_receipt': 'context_receipt',
        'episode': 'episode',
        'is_delivered': 'is_delivered',
        'is_org_promotion_allowed': 'is_org_promotion_allowed',
        'org_id': 'org_id',
        'recall_outcome': 'recall_outcome'
    }

    def __init__(self, agent_name=None, context_receipt=None, episode=None, is_delivered=None, is_org_promotion_allowed=None, org_id=None, recall_outcome=None):  # noqa: E501
        """ReinforceRequest - a model defined in Swagger"""  # noqa: E501
        self._agent_name = None
        self._context_receipt = None
        self._episode = None
        self._is_delivered = None
        self._is_org_promotion_allowed = None
        self._org_id = None
        self._recall_outcome = None
        self.discriminator = None
        self.agent_name = agent_name
        if context_receipt is not None:
            self.context_receipt = context_receipt
        self.episode = episode
        if is_delivered is not None:
            self.is_delivered = is_delivered
        if is_org_promotion_allowed is not None:
            self.is_org_promotion_allowed = is_org_promotion_allowed
        if org_id is not None:
            self.org_id = org_id
        if recall_outcome is not None:
            self.recall_outcome = recall_outcome

    @property
    def agent_name(self):
        """Gets the agent_name of this ReinforceRequest.  # noqa: E501

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, a write-scoped call (`agents:write`) creates a minimal learning agent in your tenant. `POST /resolve` with only `agents:read` looks up an existing name and does not insert. Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :return: The agent_name of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_name

    @agent_name.setter
    def agent_name(self, agent_name):
        """Sets the agent_name of this ReinforceRequest.

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, a write-scoped call (`agents:write`) creates a minimal learning agent in your tenant. `POST /resolve` with only `agents:read` looks up an existing name and does not insert. Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :param agent_name: The agent_name of this ReinforceRequest.  # noqa: E501
        :type: object
        """
        if agent_name is None:
            raise ValueError("Invalid value for `agent_name`, must not be `None`")  # noqa: E501

        self._agent_name = agent_name

    @property
    def context_receipt(self):
        """Gets the context_receipt of this ReinforceRequest.  # noqa: E501

        The host's record of the context block as its editor accepted it, used to confirm which offered learnings the model was actually shown. A learning no receipt reports as rendered credits nothing, so a host that omits this earns no reinforcement. Send the artefact the editor produced, never the text this client emitted: an echo of what was sent asserts the very thing the receipt exists to evidence. An over-cap receipt is clipped when folded rather than refused, because refusing it would cost the run its whole reinforcement and not merely its evidence; the bound on this field is far above that clip and exists only to stop an unbounded body.  # noqa: E501

        :return: The context_receipt of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._context_receipt

    @context_receipt.setter
    def context_receipt(self, context_receipt):
        """Sets the context_receipt of this ReinforceRequest.

        The host's record of the context block as its editor accepted it, used to confirm which offered learnings the model was actually shown. A learning no receipt reports as rendered credits nothing, so a host that omits this earns no reinforcement. Send the artefact the editor produced, never the text this client emitted: an echo of what was sent asserts the very thing the receipt exists to evidence. An over-cap receipt is clipped when folded rather than refused, because refusing it would cost the run its whole reinforcement and not merely its evidence; the bound on this field is far above that clip and exists only to stop an unbounded body.  # noqa: E501

        :param context_receipt: The context_receipt of this ReinforceRequest.  # noqa: E501
        :type: object
        """

        self._context_receipt = context_receipt

    @property
    def episode(self):
        """Gets the episode of this ReinforceRequest.  # noqa: E501

        Completed episode using the same caller-owned `run_id` supplied to resolve.  # noqa: E501

        :return: The episode of this ReinforceRequest.  # noqa: E501
        :rtype: EpisodeModel
        """
        return self._episode

    @episode.setter
    def episode(self, episode):
        """Sets the episode of this ReinforceRequest.

        Completed episode using the same caller-owned `run_id` supplied to resolve.  # noqa: E501

        :param episode: The episode of this ReinforceRequest.  # noqa: E501
        :type: EpisodeModel
        """
        if episode is None:
            raise ValueError("Invalid value for `episode`, must not be `None`")  # noqa: E501

        self._episode = episode

    @property
    def is_delivered(self):
        """Gets the is_delivered of this ReinforceRequest.  # noqa: E501

        Whether the recall reached the model on this turn. Omit it and an absent `context_receipt` has two readings, a run that was shown its learnings and lost the evidence and a run that was never shown them at all, and only the first is a defect. NULL means the client did not say.  # noqa: E501

        :return: The is_delivered of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._is_delivered

    @is_delivered.setter
    def is_delivered(self, is_delivered):
        """Sets the is_delivered of this ReinforceRequest.

        Whether the recall reached the model on this turn. Omit it and an absent `context_receipt` has two readings, a run that was shown its learnings and lost the evidence and a run that was never shown them at all, and only the first is a defect. NULL means the client did not say.  # noqa: E501

        :param is_delivered: The is_delivered of this ReinforceRequest.  # noqa: E501
        :type: object
        """

        self._is_delivered = is_delivered

    @property
    def is_org_promotion_allowed(self):
        """Gets the is_org_promotion_allowed of this ReinforceRequest.  # noqa: E501

        Whether eligible learnings may be considered for organisation sharing.  # noqa: E501

        :return: The is_org_promotion_allowed of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._is_org_promotion_allowed

    @is_org_promotion_allowed.setter
    def is_org_promotion_allowed(self, is_org_promotion_allowed):
        """Sets the is_org_promotion_allowed of this ReinforceRequest.

        Whether eligible learnings may be considered for organisation sharing.  # noqa: E501

        :param is_org_promotion_allowed: The is_org_promotion_allowed of this ReinforceRequest.  # noqa: E501
        :type: object
        """

        self._is_org_promotion_allowed = is_org_promotion_allowed

    @property
    def org_id(self):
        """Gets the org_id of this ReinforceRequest.  # noqa: E501

        Optional caller-owned organisation reference.  # noqa: E501

        :return: The org_id of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this ReinforceRequest.

        Optional caller-owned organisation reference.  # noqa: E501

        :param org_id: The org_id of this ReinforceRequest.  # noqa: E501
        :type: object
        """

        self._org_id = org_id

    @property
    def recall_outcome(self):
        """Gets the recall_outcome of this ReinforceRequest.  # noqa: E501

        Why the recall did not produce a receipt, from a closed set. Distinguishes a resolve that timed out or failed, a stash no tool event ever showed, and a transcript whose format the client no longer recognises, which is the one that silently ends the whole credit path. Sending this without `is_delivered` is enough: the flag is derived from it. Sending both with different meanings is refused.  # noqa: E501

        :return: The recall_outcome of this ReinforceRequest.  # noqa: E501
        :rtype: object
        """
        return self._recall_outcome

    @recall_outcome.setter
    def recall_outcome(self, recall_outcome):
        """Sets the recall_outcome of this ReinforceRequest.

        Why the recall did not produce a receipt, from a closed set. Distinguishes a resolve that timed out or failed, a stash no tool event ever showed, and a transcript whose format the client no longer recognises, which is the one that silently ends the whole credit path. Sending this without `is_delivered` is enough: the flag is derived from it. Sending both with different meanings is refused.  # noqa: E501

        :param recall_outcome: The recall_outcome of this ReinforceRequest.  # noqa: E501
        :type: object
        """

        self._recall_outcome = recall_outcome

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReinforceRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReinforceRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
