# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReportingDefaultsPutRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'constants': 'ReportingConstants',
        'is_illustrative': 'object'
    }

    attribute_map = {
        'constants': 'constants',
        'is_illustrative': 'is_illustrative'
    }

    def __init__(self, constants=None, is_illustrative=None):  # noqa: E501
        """ReportingDefaultsPutRequest - a model defined in Swagger"""  # noqa: E501
        self._constants = None
        self._is_illustrative = None
        self.discriminator = None
        self.constants = constants
        if is_illustrative is not None:
            self.is_illustrative = is_illustrative

    @property
    def constants(self):
        """Gets the constants of this ReportingDefaultsPutRequest.  # noqa: E501


        :return: The constants of this ReportingDefaultsPutRequest.  # noqa: E501
        :rtype: ReportingConstants
        """
        return self._constants

    @constants.setter
    def constants(self, constants):
        """Sets the constants of this ReportingDefaultsPutRequest.


        :param constants: The constants of this ReportingDefaultsPutRequest.  # noqa: E501
        :type: ReportingConstants
        """
        if constants is None:
            raise ValueError("Invalid value for `constants`, must not be `None`")  # noqa: E501

        self._constants = constants

    @property
    def is_illustrative(self):
        """Gets the is_illustrative of this ReportingDefaultsPutRequest.  # noqa: E501


        :return: The is_illustrative of this ReportingDefaultsPutRequest.  # noqa: E501
        :rtype: object
        """
        return self._is_illustrative

    @is_illustrative.setter
    def is_illustrative(self, is_illustrative):
        """Sets the is_illustrative of this ReportingDefaultsPutRequest.


        :param is_illustrative: The is_illustrative of this ReportingDefaultsPutRequest.  # noqa: E501
        :type: object
        """

        self._is_illustrative = is_illustrative

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReportingDefaultsPutRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReportingDefaultsPutRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
