# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

from hyperstruck.models.resolve_purpose import ResolvePurpose

class ResolveRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_name': 'object',
        'available_tools': 'object',
        'goal': 'object',
        'max_learnings': 'object',
        'model_context_window': 'object',
        'org_id': 'object',
        'resolve_idempotency_key': 'object',
        'resolve_purpose': 'ResolvePurpose',
        'retrieval': 'object',
        'run_id': 'object',
        'source_framework': 'object'
    }

    attribute_map = {
        'agent_name': 'agent_name',
        'available_tools': 'available_tools',
        'goal': 'goal',
        'max_learnings': 'max_learnings',
        'model_context_window': 'model_context_window',
        'org_id': 'org_id',
        'resolve_idempotency_key': 'resolve_idempotency_key',
        'resolve_purpose': 'resolve_purpose',
        'retrieval': 'retrieval',
        'run_id': 'run_id',
        'source_framework': 'source_framework'
    }

    def __init__(self, agent_name=None, available_tools=None, goal=None, max_learnings=None, model_context_window=None, org_id=None, resolve_idempotency_key=None, resolve_purpose=None, retrieval=None, run_id=None, source_framework=None):  # noqa: E501
        """ResolveRequest - a model defined in Swagger"""  # noqa: E501
        self._agent_name = None
        self._available_tools = None
        self._goal = None
        self._max_learnings = None
        self._model_context_window = None
        self._org_id = None
        self._resolve_idempotency_key = None
        self._resolve_purpose = None
        self._retrieval = None
        self._run_id = None
        self._source_framework = None
        self.discriminator = None
        self.agent_name = agent_name
        if available_tools is not None:
            self.available_tools = available_tools
        self.goal = goal
        if max_learnings is not None:
            self.max_learnings = max_learnings
        if model_context_window is not None:
            self.model_context_window = model_context_window
        if org_id is not None:
            self.org_id = org_id
        if resolve_idempotency_key is not None:
            self.resolve_idempotency_key = resolve_idempotency_key
        if resolve_purpose is not None:
            self.resolve_purpose = resolve_purpose
        if retrieval is not None:
            self.retrieval = retrieval
        self.run_id = run_id
        if source_framework is not None:
            self.source_framework = source_framework

    @property
    def agent_name(self):
        """Gets the agent_name of this ResolveRequest.  # noqa: E501

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, the platform creates one automatically on the first boundary call (a minimal learning agent scoped to your tenant). Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :return: The agent_name of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._agent_name

    @agent_name.setter
    def agent_name(self, agent_name):
        """Sets the agent_name of this ResolveRequest.

        Human-readable agent name, unique within your tenant. This is not the hosted agent UUID used in `/agents/{agent_id}` REST paths. If no agent with this name exists yet, the platform creates one automatically on the first boundary call (a minimal learning agent scoped to your tenant). Reuse the same name on resolve, observe, reinforce, and distill to target the same learning corpus. Clients conventionally namespace an agent-loop `run_id` as `<agent_name>:...`; if yours does, avoid the name `distill`, because `distill:` is reserved for corpus distillation run ids and every agent-loop write would be refused.  # noqa: E501

        :param agent_name: The agent_name of this ResolveRequest.  # noqa: E501
        :type: object
        """
        if agent_name is None:
            raise ValueError("Invalid value for `agent_name`, must not be `None`")  # noqa: E501

        self._agent_name = agent_name

    @property
    def available_tools(self):
        """Gets the available_tools of this ResolveRequest.  # noqa: E501


        :return: The available_tools of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._available_tools

    @available_tools.setter
    def available_tools(self, available_tools):
        """Sets the available_tools of this ResolveRequest.


        :param available_tools: The available_tools of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._available_tools = available_tools

    @property
    def goal(self):
        """Gets the goal of this ResolveRequest.  # noqa: E501

        Goal about to be attempted by the external agent.  # noqa: E501

        :return: The goal of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._goal

    @goal.setter
    def goal(self, goal):
        """Sets the goal of this ResolveRequest.

        Goal about to be attempted by the external agent.  # noqa: E501

        :param goal: The goal of this ResolveRequest.  # noqa: E501
        :type: object
        """
        if goal is None:
            raise ValueError("Invalid value for `goal`, must not be `None`")  # noqa: E501

        self._goal = goal

    @property
    def max_learnings(self):
        """Gets the max_learnings of this ResolveRequest.  # noqa: E501


        :return: The max_learnings of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._max_learnings

    @max_learnings.setter
    def max_learnings(self, max_learnings):
        """Sets the max_learnings of this ResolveRequest.


        :param max_learnings: The max_learnings of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._max_learnings = max_learnings

    @property
    def model_context_window(self):
        """Gets the model_context_window of this ResolveRequest.  # noqa: E501


        :return: The model_context_window of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._model_context_window

    @model_context_window.setter
    def model_context_window(self, model_context_window):
        """Sets the model_context_window of this ResolveRequest.


        :param model_context_window: The model_context_window of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._model_context_window = model_context_window

    @property
    def org_id(self):
        """Gets the org_id of this ResolveRequest.  # noqa: E501

        Optional caller-owned organisation reference.  # noqa: E501

        :return: The org_id of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this ResolveRequest.

        Optional caller-owned organisation reference.  # noqa: E501

        :param org_id: The org_id of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._org_id = org_id

    @property
    def resolve_idempotency_key(self):
        """Gets the resolve_idempotency_key of this ResolveRequest.  # noqa: E501

        Opaque per-recall idempotency key, scoped to this run. Supply a value that is stable across retries of one recall and distinct across genuine recalls (a turn id, milestone id, or UUID) to recall more than once in a run: each distinct key accumulates its offers and is charged once; a retry with the same key neither double-charges nor double-records. Omit for a single recall per run (the default).  # noqa: E501

        :return: The resolve_idempotency_key of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._resolve_idempotency_key

    @resolve_idempotency_key.setter
    def resolve_idempotency_key(self, resolve_idempotency_key):
        """Sets the resolve_idempotency_key of this ResolveRequest.

        Opaque per-recall idempotency key, scoped to this run. Supply a value that is stable across retries of one recall and distinct across genuine recalls (a turn id, milestone id, or UUID) to recall more than once in a run: each distinct key accumulates its offers and is charged once; a retry with the same key neither double-charges nor double-records. Omit for a single recall per run (the default).  # noqa: E501

        :param resolve_idempotency_key: The resolve_idempotency_key of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._resolve_idempotency_key = resolve_idempotency_key

    @property
    def resolve_purpose(self):
        """Gets the resolve_purpose of this ResolveRequest.  # noqa: E501

        Why this recall is being made. `agent_loop` covers executing agents and agent-owned integrations, attributing a non-empty response to reporting. `explicit_recall` is human-facing inspection and does not contribute to automated-loop value.  # noqa: E501

        :return: The resolve_purpose of this ResolveRequest.  # noqa: E501
        :rtype: ResolvePurpose
        """
        return self._resolve_purpose

    @resolve_purpose.setter
    def resolve_purpose(self, resolve_purpose):
        """Sets the resolve_purpose of this ResolveRequest.

        Why this recall is being made. `agent_loop` covers executing agents and agent-owned integrations, attributing a non-empty response to reporting. `explicit_recall` is human-facing inspection and does not contribute to automated-loop value.  # noqa: E501

        :param resolve_purpose: The resolve_purpose of this ResolveRequest.  # noqa: E501
        :type: ResolvePurpose
        """

        self._resolve_purpose = ResolvePurpose(resolve_purpose)

    @property
    def retrieval(self):
        """Gets the retrieval of this ResolveRequest.  # noqa: E501

        Retrieval depth. `fast` prioritises response time; `full` may return richer contextual relationships at higher latency.  # noqa: E501

        :return: The retrieval of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._retrieval

    @retrieval.setter
    def retrieval(self, retrieval):
        """Sets the retrieval of this ResolveRequest.

        Retrieval depth. `fast` prioritises response time; `full` may return richer contextual relationships at higher latency.  # noqa: E501

        :param retrieval: The retrieval of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._retrieval = retrieval

    @property
    def run_id(self):
        """Gets the run_id of this ResolveRequest.  # noqa: E501

        Caller-created correlation key. Reuse it with observe and reinforce; it does not reference a hosted `/runs/{run_id}` resource, and must not start with `distill:`, which is reserved for distillation jobs.  # noqa: E501

        :return: The run_id of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this ResolveRequest.

        Caller-created correlation key. Reuse it with observe and reinforce; it does not reference a hosted `/runs/{run_id}` resource, and must not start with `distill:`, which is reserved for distillation jobs.  # noqa: E501

        :param run_id: The run_id of this ResolveRequest.  # noqa: E501
        :type: object
        """
        if run_id is None:
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501

        self._run_id = run_id

    @property
    def source_framework(self):
        """Gets the source_framework of this ResolveRequest.  # noqa: E501

        Producing host/framework (e.g. 'mcp:cursor'), used to attribute the per-host funnel. Optional; backfilled from the episode at write-back. `unknown` is reserved: the loop-closure funnel groups runs with no attribution under that label and excludes them from alerting, so a value equal to it is normalised to unset rather than stored as a host.  # noqa: E501

        :return: The source_framework of this ResolveRequest.  # noqa: E501
        :rtype: object
        """
        return self._source_framework

    @source_framework.setter
    def source_framework(self, source_framework):
        """Sets the source_framework of this ResolveRequest.

        Producing host/framework (e.g. 'mcp:cursor'), used to attribute the per-host funnel. Optional; backfilled from the episode at write-back. `unknown` is reserved: the loop-closure funnel groups runs with no attribution under that label and excludes them from alerting, so a value equal to it is normalised to unset rather than stored as a host.  # noqa: E501

        :param source_framework: The source_framework of this ResolveRequest.  # noqa: E501
        :type: object
        """

        self._source_framework = source_framework

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResolveRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResolveRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
