# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResolvedLearning(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'counted_example_count': 'object',
        'distinct_session_count': 'object',
        'examples': 'object',
        'id': 'object',
        'newest_source_time': 'object',
        'origin': 'object'
    }

    attribute_map = {
        'counted_example_count': 'counted_example_count',
        'distinct_session_count': 'distinct_session_count',
        'examples': 'examples',
        'id': 'id',
        'newest_source_time': 'newest_source_time',
        'origin': 'origin'
    }

    def __init__(self, counted_example_count=None, distinct_session_count=None, examples=None, id=None, newest_source_time=None, origin=None):  # noqa: E501
        """ResolvedLearning - a model defined in Swagger"""  # noqa: E501
        self._counted_example_count = None
        self._distinct_session_count = None
        self._examples = None
        self._id = None
        self._newest_source_time = None
        self._origin = None
        self.discriminator = None
        if counted_example_count is not None:
            self.counted_example_count = counted_example_count
        if distinct_session_count is not None:
            self.distinct_session_count = distinct_session_count
        if examples is not None:
            self.examples = examples
        self.id = id
        if newest_source_time is not None:
            self.newest_source_time = newest_source_time
        self.origin = origin

    @property
    def counted_example_count(self):
        """Gets the counted_example_count of this ResolvedLearning.  # noqa: E501


        :return: The counted_example_count of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._counted_example_count

    @counted_example_count.setter
    def counted_example_count(self, counted_example_count):
        """Sets the counted_example_count of this ResolvedLearning.


        :param counted_example_count: The counted_example_count of this ResolvedLearning.  # noqa: E501
        :type: object
        """

        self._counted_example_count = counted_example_count

    @property
    def distinct_session_count(self):
        """Gets the distinct_session_count of this ResolvedLearning.  # noqa: E501


        :return: The distinct_session_count of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._distinct_session_count

    @distinct_session_count.setter
    def distinct_session_count(self, distinct_session_count):
        """Sets the distinct_session_count of this ResolvedLearning.


        :param distinct_session_count: The distinct_session_count of this ResolvedLearning.  # noqa: E501
        :type: object
        """

        self._distinct_session_count = distinct_session_count

    @property
    def examples(self):
        """Gets the examples of this ResolvedLearning.  # noqa: E501


        :return: The examples of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._examples

    @examples.setter
    def examples(self, examples):
        """Sets the examples of this ResolvedLearning.


        :param examples: The examples of this ResolvedLearning.  # noqa: E501
        :type: object
        """

        self._examples = examples

    @property
    def id(self):
        """Gets the id of this ResolvedLearning.  # noqa: E501


        :return: The id of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ResolvedLearning.


        :param id: The id of this ResolvedLearning.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def newest_source_time(self):
        """Gets the newest_source_time of this ResolvedLearning.  # noqa: E501


        :return: The newest_source_time of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._newest_source_time

    @newest_source_time.setter
    def newest_source_time(self, newest_source_time):
        """Sets the newest_source_time of this ResolvedLearning.


        :param newest_source_time: The newest_source_time of this ResolvedLearning.  # noqa: E501
        :type: object
        """

        self._newest_source_time = newest_source_time

    @property
    def origin(self):
        """Gets the origin of this ResolvedLearning.  # noqa: E501


        :return: The origin of this ResolvedLearning.  # noqa: E501
        :rtype: object
        """
        return self._origin

    @origin.setter
    def origin(self, origin):
        """Sets the origin of this ResolvedLearning.


        :param origin: The origin of this ResolvedLearning.  # noqa: E501
        :type: object
        """
        if origin is None:
            raise ValueError("Invalid value for `origin`, must not be `None`")  # noqa: E501

        self._origin = origin

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResolvedLearning, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResolvedLearning):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
