# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResolvedEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'claims': 'object',
        'held_for_review_count': 'object',
        'name': 'object',
        'salience': 'object',
        'truncated_count': 'object'
    }

    attribute_map = {
        'claims': 'claims',
        'held_for_review_count': 'held_for_review_count',
        'name': 'name',
        'salience': 'salience',
        'truncated_count': 'truncated_count'
    }

    def __init__(self, claims=None, held_for_review_count=None, name=None, salience=None, truncated_count=None):  # noqa: E501
        """ResolvedEntity - a model defined in Swagger"""  # noqa: E501
        self._claims = None
        self._held_for_review_count = None
        self._name = None
        self._salience = None
        self._truncated_count = None
        self.discriminator = None
        if claims is not None:
            self.claims = claims
        if held_for_review_count is not None:
            self.held_for_review_count = held_for_review_count
        self.name = name
        self.salience = salience
        if truncated_count is not None:
            self.truncated_count = truncated_count

    @property
    def claims(self):
        """Gets the claims of this ResolvedEntity.  # noqa: E501


        :return: The claims of this ResolvedEntity.  # noqa: E501
        :rtype: object
        """
        return self._claims

    @claims.setter
    def claims(self, claims):
        """Sets the claims of this ResolvedEntity.


        :param claims: The claims of this ResolvedEntity.  # noqa: E501
        :type: object
        """

        self._claims = claims

    @property
    def held_for_review_count(self):
        """Gets the held_for_review_count of this ResolvedEntity.  # noqa: E501

        Open claims about this entity that are quarantined, so they were never bound and are absent above. A non-zero count is the difference between an entity nobody knows anything about and one whose facts are waiting on a curator. List them with GET /agents/{agent_id}/claims, which needs the `claims:read` scope that recall's own `agents:read` does not imply.  # noqa: E501

        :return: The held_for_review_count of this ResolvedEntity.  # noqa: E501
        :rtype: object
        """
        return self._held_for_review_count

    @held_for_review_count.setter
    def held_for_review_count(self, held_for_review_count):
        """Sets the held_for_review_count of this ResolvedEntity.

        Open claims about this entity that are quarantined, so they were never bound and are absent above. A non-zero count is the difference between an entity nobody knows anything about and one whose facts are waiting on a curator. List them with GET /agents/{agent_id}/claims, which needs the `claims:read` scope that recall's own `agents:read` does not imply.  # noqa: E501

        :param held_for_review_count: The held_for_review_count of this ResolvedEntity.  # noqa: E501
        :type: object
        """

        self._held_for_review_count = held_for_review_count

    @property
    def name(self):
        """Gets the name of this ResolvedEntity.  # noqa: E501


        :return: The name of this ResolvedEntity.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ResolvedEntity.


        :param name: The name of this ResolvedEntity.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def salience(self):
        """Gets the salience of this ResolvedEntity.  # noqa: E501


        :return: The salience of this ResolvedEntity.  # noqa: E501
        :rtype: object
        """
        return self._salience

    @salience.setter
    def salience(self, salience):
        """Sets the salience of this ResolvedEntity.


        :param salience: The salience of this ResolvedEntity.  # noqa: E501
        :type: object
        """
        if salience is None:
            raise ValueError("Invalid value for `salience`, must not be `None`")  # noqa: E501

        self._salience = salience

    @property
    def truncated_count(self):
        """Gets the truncated_count of this ResolvedEntity.  # noqa: E501

        Facts that cleared the trust floor and fell outside this lane's per-entity cap. More of the same, not withheld.  # noqa: E501

        :return: The truncated_count of this ResolvedEntity.  # noqa: E501
        :rtype: object
        """
        return self._truncated_count

    @truncated_count.setter
    def truncated_count(self, truncated_count):
        """Sets the truncated_count of this ResolvedEntity.

        Facts that cleared the trust floor and fell outside this lane's per-entity cap. More of the same, not withheld.  # noqa: E501

        :param truncated_count: The truncated_count of this ResolvedEntity.  # noqa: E501
        :type: object
        """

        self._truncated_count = truncated_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResolvedEntity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResolvedEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
