# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RunStatusResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'claim_count': 'object',
        'corpus_items_lost': 'object',
        'corpus_items_with_claims': 'object',
        'finished_at': 'object',
        'learning_count': 'object',
        'run_id': 'object',
        'run_kind': 'object',
        'state': 'RunState',
        'zero_reason': 'object'
    }

    attribute_map = {
        'claim_count': 'claim_count',
        'corpus_items_lost': 'corpus_items_lost',
        'corpus_items_with_claims': 'corpus_items_with_claims',
        'finished_at': 'finished_at',
        'learning_count': 'learning_count',
        'run_id': 'run_id',
        'run_kind': 'run_kind',
        'state': 'state',
        'zero_reason': 'zero_reason'
    }

    def __init__(self, claim_count=None, corpus_items_lost=None, corpus_items_with_claims=None, finished_at=None, learning_count=None, run_id=None, run_kind=None, state=None, zero_reason=None):  # noqa: E501
        """RunStatusResponse - a model defined in Swagger"""  # noqa: E501
        self._claim_count = None
        self._corpus_items_lost = None
        self._corpus_items_with_claims = None
        self._finished_at = None
        self._learning_count = None
        self._run_id = None
        self._run_kind = None
        self._state = None
        self._zero_reason = None
        self.discriminator = None
        if claim_count is not None:
            self.claim_count = claim_count
        if corpus_items_lost is not None:
            self.corpus_items_lost = corpus_items_lost
        if corpus_items_with_claims is not None:
            self.corpus_items_with_claims = corpus_items_with_claims
        if finished_at is not None:
            self.finished_at = finished_at
        if learning_count is not None:
            self.learning_count = learning_count
        self.run_id = run_id
        self.run_kind = run_kind
        self.state = state
        if zero_reason is not None:
            self.zero_reason = zero_reason

    @property
    def claim_count(self):
        """Gets the claim_count of this RunStatusResponse.  # noqa: E501

        Claims written. Null until the job finishes, which is not zero.  # noqa: E501

        :return: The claim_count of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._claim_count

    @claim_count.setter
    def claim_count(self, claim_count):
        """Sets the claim_count of this RunStatusResponse.

        Claims written. Null until the job finishes, which is not zero.  # noqa: E501

        :param claim_count: The claim_count of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._claim_count = claim_count

    @property
    def corpus_items_lost(self):
        """Gets the corpus_items_lost of this RunStatusResponse.  # noqa: E501

        Evidence items in a pass that failed, so they were never read. Non-zero means part of the corpus was not seen and resending is worthwhile; the claims from every other pass are still stored.  # noqa: E501

        :return: The corpus_items_lost of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._corpus_items_lost

    @corpus_items_lost.setter
    def corpus_items_lost(self, corpus_items_lost):
        """Sets the corpus_items_lost of this RunStatusResponse.

        Evidence items in a pass that failed, so they were never read. Non-zero means part of the corpus was not seen and resending is worthwhile; the claims from every other pass are still stored.  # noqa: E501

        :param corpus_items_lost: The corpus_items_lost of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._corpus_items_lost = corpus_items_lost

    @property
    def corpus_items_with_claims(self):
        """Gets the corpus_items_with_claims of this RunStatusResponse.  # noqa: E501

        Evidence items that produced at least one claim. Null until the job finishes, and 0 on a job that carried no corpus. Read beside items_lost: a corpus that held few facts and one the extraction skipped are different answers, and only one is worth resending.  # noqa: E501

        :return: The corpus_items_with_claims of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._corpus_items_with_claims

    @corpus_items_with_claims.setter
    def corpus_items_with_claims(self, corpus_items_with_claims):
        """Sets the corpus_items_with_claims of this RunStatusResponse.

        Evidence items that produced at least one claim. Null until the job finishes, and 0 on a job that carried no corpus. Read beside items_lost: a corpus that held few facts and one the extraction skipped are different answers, and only one is worth resending.  # noqa: E501

        :param corpus_items_with_claims: The corpus_items_with_claims of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._corpus_items_with_claims = corpus_items_with_claims

    @property
    def finished_at(self):
        """Gets the finished_at of this RunStatusResponse.  # noqa: E501


        :return: The finished_at of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._finished_at

    @finished_at.setter
    def finished_at(self, finished_at):
        """Sets the finished_at of this RunStatusResponse.


        :param finished_at: The finished_at of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._finished_at = finished_at

    @property
    def learning_count(self):
        """Gets the learning_count of this RunStatusResponse.  # noqa: E501

        Learnings stored. Null until the job finishes, which is not zero.  # noqa: E501

        :return: The learning_count of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._learning_count

    @learning_count.setter
    def learning_count(self, learning_count):
        """Sets the learning_count of this RunStatusResponse.

        Learnings stored. Null until the job finishes, which is not zero.  # noqa: E501

        :param learning_count: The learning_count of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._learning_count = learning_count

    @property
    def run_id(self):
        """Gets the run_id of this RunStatusResponse.  # noqa: E501


        :return: The run_id of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this RunStatusResponse.


        :param run_id: The run_id of this RunStatusResponse.  # noqa: E501
        :type: object
        """
        if run_id is None:
            raise ValueError("Invalid value for `run_id`, must not be `None`")  # noqa: E501

        self._run_id = run_id

    @property
    def run_kind(self):
        """Gets the run_kind of this RunStatusResponse.  # noqa: E501


        :return: The run_kind of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._run_kind

    @run_kind.setter
    def run_kind(self, run_kind):
        """Sets the run_kind of this RunStatusResponse.


        :param run_kind: The run_kind of this RunStatusResponse.  # noqa: E501
        :type: object
        """
        if run_kind is None:
            raise ValueError("Invalid value for `run_kind`, must not be `None`")  # noqa: E501

        self._run_kind = run_kind

    @property
    def state(self):
        """Gets the state of this RunStatusResponse.  # noqa: E501


        :return: The state of this RunStatusResponse.  # noqa: E501
        :rtype: RunState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this RunStatusResponse.


        :param state: The state of this RunStatusResponse.  # noqa: E501
        :type: RunState
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def zero_reason(self):
        """Gets the zero_reason of this RunStatusResponse.  # noqa: E501

        Why a count came back zero. Set only when one did.  # noqa: E501

        :return: The zero_reason of this RunStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._zero_reason

    @zero_reason.setter
    def zero_reason(self, zero_reason):
        """Sets the zero_reason of this RunStatusResponse.

        Why a count came back zero. Set only when one did.  # noqa: E501

        :param zero_reason: The zero_reason of this RunStatusResponse.  # noqa: E501
        :type: object
        """

        self._zero_reason = zero_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunStatusResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunStatusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
