# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SessionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'agent_id': 'object',
        'status': 'object',
        'title': 'object',
        'latest_run_id': 'object',
        'metadata': 'object',
        'created_at': 'object'
    }

    attribute_map = {
        'id': 'id',
        'agent_id': 'agent_id',
        'status': 'status',
        'title': 'title',
        'latest_run_id': 'latest_run_id',
        'metadata': 'metadata',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, agent_id=None, status=None, title=None, latest_run_id=None, metadata=None, created_at=None):  # noqa: E501
        """SessionResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._agent_id = None
        self._status = None
        self._title = None
        self._latest_run_id = None
        self._metadata = None
        self._created_at = None
        self.discriminator = None
        self.id = id
        self.agent_id = agent_id
        self.status = status
        self.title = title
        if latest_run_id is not None:
            self.latest_run_id = latest_run_id
        if metadata is not None:
            self.metadata = metadata
        self.created_at = created_at

    @property
    def id(self):
        """Gets the id of this SessionResponse.  # noqa: E501


        :return: The id of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SessionResponse.


        :param id: The id of this SessionResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def agent_id(self):
        """Gets the agent_id of this SessionResponse.  # noqa: E501


        :return: The agent_id of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this SessionResponse.


        :param agent_id: The agent_id of this SessionResponse.  # noqa: E501
        :type: object
        """
        if agent_id is None:
            raise ValueError("Invalid value for `agent_id`, must not be `None`")  # noqa: E501

        self._agent_id = agent_id

    @property
    def status(self):
        """Gets the status of this SessionResponse.  # noqa: E501


        :return: The status of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SessionResponse.


        :param status: The status of this SessionResponse.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def title(self):
        """Gets the title of this SessionResponse.  # noqa: E501


        :return: The title of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SessionResponse.


        :param title: The title of this SessionResponse.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def latest_run_id(self):
        """Gets the latest_run_id of this SessionResponse.  # noqa: E501


        :return: The latest_run_id of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._latest_run_id

    @latest_run_id.setter
    def latest_run_id(self, latest_run_id):
        """Sets the latest_run_id of this SessionResponse.


        :param latest_run_id: The latest_run_id of this SessionResponse.  # noqa: E501
        :type: object
        """

        self._latest_run_id = latest_run_id

    @property
    def metadata(self):
        """Gets the metadata of this SessionResponse.  # noqa: E501


        :return: The metadata of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this SessionResponse.


        :param metadata: The metadata of this SessionResponse.  # noqa: E501
        :type: object
        """

        self._metadata = metadata

    @property
    def created_at(self):
        """Gets the created_at of this SessionResponse.  # noqa: E501


        :return: The created_at of this SessionResponse.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SessionResponse.


        :param created_at: The created_at of this SessionResponse.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SessionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
