# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SpaceResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'kind': 'SpaceKind',
        'department_id': 'object',
        'owner_identity_user_id': 'object',
        'agent_count': 'object',
        'created_at': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'kind': 'kind',
        'department_id': 'department_id',
        'owner_identity_user_id': 'owner_identity_user_id',
        'agent_count': 'agent_count',
        'created_at': 'created_at'
    }

    def __init__(self, id=None, name=None, kind=None, department_id=None, owner_identity_user_id=None, agent_count=None, created_at=None):  # noqa: E501
        """SpaceResponse - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._kind = None
        self._department_id = None
        self._owner_identity_user_id = None
        self._agent_count = None
        self._created_at = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.kind = kind
        if department_id is not None:
            self.department_id = department_id
        if owner_identity_user_id is not None:
            self.owner_identity_user_id = owner_identity_user_id
        self.agent_count = agent_count
        self.created_at = created_at

    @property
    def id(self):
        """Gets the id of this SpaceResponse.  # noqa: E501


        :return: The id of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SpaceResponse.


        :param id: The id of this SpaceResponse.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this SpaceResponse.  # noqa: E501


        :return: The name of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SpaceResponse.


        :param name: The name of this SpaceResponse.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def kind(self):
        """Gets the kind of this SpaceResponse.  # noqa: E501


        :return: The kind of this SpaceResponse.  # noqa: E501
        :rtype: SpaceKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind):
        """Sets the kind of this SpaceResponse.


        :param kind: The kind of this SpaceResponse.  # noqa: E501
        :type: SpaceKind
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def department_id(self):
        """Gets the department_id of this SpaceResponse.  # noqa: E501

        WorkOS directory group id; set iff kind == 'department'.  # noqa: E501

        :return: The department_id of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._department_id

    @department_id.setter
    def department_id(self, department_id):
        """Sets the department_id of this SpaceResponse.

        WorkOS directory group id; set iff kind == 'department'.  # noqa: E501

        :param department_id: The department_id of this SpaceResponse.  # noqa: E501
        :type: object
        """

        self._department_id = department_id

    @property
    def owner_identity_user_id(self):
        """Gets the owner_identity_user_id of this SpaceResponse.  # noqa: E501

        Steward identity user id; set iff kind == 'personal'.  # noqa: E501

        :return: The owner_identity_user_id of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._owner_identity_user_id

    @owner_identity_user_id.setter
    def owner_identity_user_id(self, owner_identity_user_id):
        """Sets the owner_identity_user_id of this SpaceResponse.

        Steward identity user id; set iff kind == 'personal'.  # noqa: E501

        :param owner_identity_user_id: The owner_identity_user_id of this SpaceResponse.  # noqa: E501
        :type: object
        """

        self._owner_identity_user_id = owner_identity_user_id

    @property
    def agent_count(self):
        """Gets the agent_count of this SpaceResponse.  # noqa: E501

        How many agents currently home in this space.  # noqa: E501

        :return: The agent_count of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._agent_count

    @agent_count.setter
    def agent_count(self, agent_count):
        """Sets the agent_count of this SpaceResponse.

        How many agents currently home in this space.  # noqa: E501

        :param agent_count: The agent_count of this SpaceResponse.  # noqa: E501
        :type: object
        """
        if agent_count is None:
            raise ValueError("Invalid value for `agent_count`, must not be `None`")  # noqa: E501

        self._agent_count = agent_count

    @property
    def created_at(self):
        """Gets the created_at of this SpaceResponse.  # noqa: E501


        :return: The created_at of this SpaceResponse.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SpaceResponse.


        :param created_at: The created_at of this SpaceResponse.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpaceResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpaceResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
