# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SplitProposalQueueItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'proposal_id': 'object',
        'agent_id': 'object',
        'entity_id': 'object',
        'canonical_name': 'object',
        'attribute_key': 'object',
        'classification': 'object',
        'status': 'object',
        'proposed_qualifier': 'object',
        'created_at': 'object'
    }

    attribute_map = {
        'proposal_id': 'proposal_id',
        'agent_id': 'agent_id',
        'entity_id': 'entity_id',
        'canonical_name': 'canonical_name',
        'attribute_key': 'attribute_key',
        'classification': 'classification',
        'status': 'status',
        'proposed_qualifier': 'proposed_qualifier',
        'created_at': 'created_at'
    }

    def __init__(self, proposal_id=None, agent_id=None, entity_id=None, canonical_name=None, attribute_key=None, classification=None, status=None, proposed_qualifier=None, created_at=None):  # noqa: E501
        """SplitProposalQueueItem - a model defined in Swagger"""  # noqa: E501
        self._proposal_id = None
        self._agent_id = None
        self._entity_id = None
        self._canonical_name = None
        self._attribute_key = None
        self._classification = None
        self._status = None
        self._proposed_qualifier = None
        self._created_at = None
        self.discriminator = None
        self.proposal_id = proposal_id
        self.agent_id = agent_id
        self.entity_id = entity_id
        self.canonical_name = canonical_name
        self.attribute_key = attribute_key
        self.classification = classification
        self.status = status
        if proposed_qualifier is not None:
            self.proposed_qualifier = proposed_qualifier
        self.created_at = created_at

    @property
    def proposal_id(self):
        """Gets the proposal_id of this SplitProposalQueueItem.  # noqa: E501


        :return: The proposal_id of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._proposal_id

    @proposal_id.setter
    def proposal_id(self, proposal_id):
        """Sets the proposal_id of this SplitProposalQueueItem.


        :param proposal_id: The proposal_id of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if proposal_id is None:
            raise ValueError("Invalid value for `proposal_id`, must not be `None`")  # noqa: E501

        self._proposal_id = proposal_id

    @property
    def agent_id(self):
        """Gets the agent_id of this SplitProposalQueueItem.  # noqa: E501


        :return: The agent_id of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._agent_id

    @agent_id.setter
    def agent_id(self, agent_id):
        """Sets the agent_id of this SplitProposalQueueItem.


        :param agent_id: The agent_id of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if agent_id is None:
            raise ValueError("Invalid value for `agent_id`, must not be `None`")  # noqa: E501

        self._agent_id = agent_id

    @property
    def entity_id(self):
        """Gets the entity_id of this SplitProposalQueueItem.  # noqa: E501


        :return: The entity_id of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this SplitProposalQueueItem.


        :param entity_id: The entity_id of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if entity_id is None:
            raise ValueError("Invalid value for `entity_id`, must not be `None`")  # noqa: E501

        self._entity_id = entity_id

    @property
    def canonical_name(self):
        """Gets the canonical_name of this SplitProposalQueueItem.  # noqa: E501


        :return: The canonical_name of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._canonical_name

    @canonical_name.setter
    def canonical_name(self, canonical_name):
        """Sets the canonical_name of this SplitProposalQueueItem.


        :param canonical_name: The canonical_name of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if canonical_name is None:
            raise ValueError("Invalid value for `canonical_name`, must not be `None`")  # noqa: E501

        self._canonical_name = canonical_name

    @property
    def attribute_key(self):
        """Gets the attribute_key of this SplitProposalQueueItem.  # noqa: E501


        :return: The attribute_key of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._attribute_key

    @attribute_key.setter
    def attribute_key(self, attribute_key):
        """Sets the attribute_key of this SplitProposalQueueItem.


        :param attribute_key: The attribute_key of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if attribute_key is None:
            raise ValueError("Invalid value for `attribute_key`, must not be `None`")  # noqa: E501

        self._attribute_key = attribute_key

    @property
    def classification(self):
        """Gets the classification of this SplitProposalQueueItem.  # noqa: E501


        :return: The classification of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._classification

    @classification.setter
    def classification(self, classification):
        """Sets the classification of this SplitProposalQueueItem.


        :param classification: The classification of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if classification is None:
            raise ValueError("Invalid value for `classification`, must not be `None`")  # noqa: E501

        self._classification = classification

    @property
    def status(self):
        """Gets the status of this SplitProposalQueueItem.  # noqa: E501


        :return: The status of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SplitProposalQueueItem.


        :param status: The status of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def proposed_qualifier(self):
        """Gets the proposed_qualifier of this SplitProposalQueueItem.  # noqa: E501


        :return: The proposed_qualifier of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._proposed_qualifier

    @proposed_qualifier.setter
    def proposed_qualifier(self, proposed_qualifier):
        """Sets the proposed_qualifier of this SplitProposalQueueItem.


        :param proposed_qualifier: The proposed_qualifier of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """

        self._proposed_qualifier = proposed_qualifier

    @property
    def created_at(self):
        """Gets the created_at of this SplitProposalQueueItem.  # noqa: E501


        :return: The created_at of this SplitProposalQueueItem.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this SplitProposalQueueItem.


        :param created_at: The created_at of this SplitProposalQueueItem.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SplitProposalQueueItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SplitProposalQueueItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
