# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StepModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'args': 'object',
        'declared_sensitivity': 'object',
        'error': 'object',
        'id': 'object',
        'is_refused': 'object',
        'name': 'object',
        'result': 'object',
        'status': 'object'
    }

    attribute_map = {
        'args': 'args',
        'declared_sensitivity': 'declared_sensitivity',
        'error': 'error',
        'id': 'id',
        'is_refused': 'is_refused',
        'name': 'name',
        'result': 'result',
        'status': 'status'
    }

    def __init__(self, args=None, declared_sensitivity=None, error=None, id=None, is_refused=None, name=None, result=None, status=None):  # noqa: E501
        """StepModel - a model defined in Swagger"""  # noqa: E501
        self._args = None
        self._declared_sensitivity = None
        self._error = None
        self._id = None
        self._is_refused = None
        self._name = None
        self._result = None
        self._status = None
        self.discriminator = None
        if args is not None:
            self.args = args
        if declared_sensitivity is not None:
            self.declared_sensitivity = declared_sensitivity
        if error is not None:
            self.error = error
        self.id = id
        if is_refused is not None:
            self.is_refused = is_refused
        self.name = name
        if result is not None:
            self.result = result
        if status is not None:
            self.status = status

    @property
    def args(self):
        """Gets the args of this StepModel.  # noqa: E501

        Arguments supplied to the tool or action.  # noqa: E501

        :return: The args of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._args

    @args.setter
    def args(self, args):
        """Sets the args of this StepModel.

        Arguments supplied to the tool or action.  # noqa: E501

        :param args: The args of this StepModel.  # noqa: E501
        :type: object
        """

        self._args = args

    @property
    def declared_sensitivity(self):
        """Gets the declared_sensitivity of this StepModel.  # noqa: E501

        Optional caller-declared metadata for this step. Sections whose value is a mapping carry per-field declarations (`args`, `result`, `result_attributes`, `result_integrity`, and the `provenance` record). Sections whose value is a string carry a single declaration, of which `subject` is the one the runtime reads: the argument key naming the entity this step's result is about.  # noqa: E501

        :return: The declared_sensitivity of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._declared_sensitivity

    @declared_sensitivity.setter
    def declared_sensitivity(self, declared_sensitivity):
        """Sets the declared_sensitivity of this StepModel.

        Optional caller-declared metadata for this step. Sections whose value is a mapping carry per-field declarations (`args`, `result`, `result_attributes`, `result_integrity`, and the `provenance` record). Sections whose value is a string carry a single declaration, of which `subject` is the one the runtime reads: the argument key naming the entity this step's result is about.  # noqa: E501

        :param declared_sensitivity: The declared_sensitivity of this StepModel.  # noqa: E501
        :type: object
        """

        self._declared_sensitivity = declared_sensitivity

    @property
    def error(self):
        """Gets the error of this StepModel.  # noqa: E501

        Human-readable failure detail when `status` is `failed`.  # noqa: E501

        :return: The error of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this StepModel.

        Human-readable failure detail when `status` is `failed`.  # noqa: E501

        :param error: The error of this StepModel.  # noqa: E501
        :type: object
        """

        self._error = error

    @property
    def id(self):
        """Gets the id of this StepModel.  # noqa: E501

        Step identifier unique within this episode.  # noqa: E501

        :return: The id of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this StepModel.

        Step identifier unique within this episode.  # noqa: E501

        :param id: The id of this StepModel.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def is_refused(self):
        """Gets the is_refused of this StepModel.  # noqa: E501

        The runtime decided this act must not happen. Valid only with `status` of `skipped` and no `error`: a step that ran and failed into a skip carries an error and is a run that tried, not one that held off. This is the signal restraint learning reads, and a `skipped` step without it reports an act that was never scheduled.  # noqa: E501

        :return: The is_refused of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._is_refused

    @is_refused.setter
    def is_refused(self, is_refused):
        """Sets the is_refused of this StepModel.

        The runtime decided this act must not happen. Valid only with `status` of `skipped` and no `error`: a step that ran and failed into a skip carries an error and is a run that tried, not one that held off. This is the signal restraint learning reads, and a `skipped` step without it reports an act that was never scheduled.  # noqa: E501

        :param is_refused: The is_refused of this StepModel.  # noqa: E501
        :type: object
        """

        self._is_refused = is_refused

    @property
    def name(self):
        """Gets the name of this StepModel.  # noqa: E501

        Tool or action name executed by the external agent.  # noqa: E501

        :return: The name of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this StepModel.

        Tool or action name executed by the external agent.  # noqa: E501

        :param name: The name of this StepModel.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def result(self):
        """Gets the result of this StepModel.  # noqa: E501

        Caller-supplied step result. Pre-redact secrets and personal data.  # noqa: E501

        :return: The result of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this StepModel.

        Caller-supplied step result. Pre-redact secrets and personal data.  # noqa: E501

        :param result: The result of this StepModel.  # noqa: E501
        :type: object
        """

        self._result = result

    @property
    def status(self):
        """Gets the status of this StepModel.  # noqa: E501

        Terminal status of this step. `skipped` covers every way a step did not run; on its own it does NOT mean the runtime refused the act. Pair it with `is_refused` to report a refusal.  # noqa: E501

        :return: The status of this StepModel.  # noqa: E501
        :rtype: object
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this StepModel.

        Terminal status of this step. `skipped` covers every way a step did not run; on its own it does NOT mean the runtime refused the act. Pair it with `is_refused` to report a refusal.  # noqa: E501

        :param status: The status of this StepModel.  # noqa: E501
        :type: object
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StepModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StepModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
