# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StoredAnswerPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'answers': 'object',
        'next_cursor': 'object'
    }

    attribute_map = {
        'answers': 'answers',
        'next_cursor': 'next_cursor'
    }

    def __init__(self, answers=None, next_cursor=None):  # noqa: E501
        """StoredAnswerPage - a model defined in Swagger"""  # noqa: E501
        self._answers = None
        self._next_cursor = None
        self.discriminator = None
        self.answers = answers
        if next_cursor is not None:
            self.next_cursor = next_cursor

    @property
    def answers(self):
        """Gets the answers of this StoredAnswerPage.  # noqa: E501


        :return: The answers of this StoredAnswerPage.  # noqa: E501
        :rtype: object
        """
        return self._answers

    @answers.setter
    def answers(self, answers):
        """Sets the answers of this StoredAnswerPage.


        :param answers: The answers of this StoredAnswerPage.  # noqa: E501
        :type: object
        """
        if answers is None:
            raise ValueError("Invalid value for `answers`, must not be `None`")  # noqa: E501

        self._answers = answers

    @property
    def next_cursor(self):
        """Gets the next_cursor of this StoredAnswerPage.  # noqa: E501

        Pass as `cursor` for the next page. Null on the last page.  # noqa: E501

        :return: The next_cursor of this StoredAnswerPage.  # noqa: E501
        :rtype: object
        """
        return self._next_cursor

    @next_cursor.setter
    def next_cursor(self, next_cursor):
        """Sets the next_cursor of this StoredAnswerPage.

        Pass as `cursor` for the next page. Null on the last page.  # noqa: E501

        :param next_cursor: The next_cursor of this StoredAnswerPage.  # noqa: E501
        :type: object
        """

        self._next_cursor = next_cursor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StoredAnswerPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StoredAnswerPage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
