# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ToolSpecModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'category': 'object',
        'description': 'object',
        'name': 'object',
        'parameters': 'object',
        'returns': 'object'
    }

    attribute_map = {
        'category': 'category',
        'description': 'description',
        'name': 'name',
        'parameters': 'parameters',
        'returns': 'returns'
    }

    def __init__(self, category=None, description=None, name=None, parameters=None, returns=None):  # noqa: E501
        """ToolSpecModel - a model defined in Swagger"""  # noqa: E501
        self._category = None
        self._description = None
        self._name = None
        self._parameters = None
        self._returns = None
        self.discriminator = None
        if category is not None:
            self.category = category
        if description is not None:
            self.description = description
        self.name = name
        if parameters is not None:
            self.parameters = parameters
        if returns is not None:
            self.returns = returns

    @property
    def category(self):
        """Gets the category of this ToolSpecModel.  # noqa: E501

        The tool's declared category. Restraint and admissibility both classify on this, and only the values Core knows are read: `read_only`, `write`, `destructive`, `external`, `delegation`. Of those, `write`, `destructive` and `external` are the side-effectful ones. Anything else, including a near-miss like `read`, is treated as declaring nothing, and a roster where nothing declares a side-effectful category cannot express that a run held off at all.  # noqa: E501

        :return: The category of this ToolSpecModel.  # noqa: E501
        :rtype: object
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this ToolSpecModel.

        The tool's declared category. Restraint and admissibility both classify on this, and only the values Core knows are read: `read_only`, `write`, `destructive`, `external`, `delegation`. Of those, `write`, `destructive` and `external` are the side-effectful ones. Anything else, including a near-miss like `read`, is treated as declaring nothing, and a roster where nothing declares a side-effectful category cannot express that a run held off at all.  # noqa: E501

        :param category: The category of this ToolSpecModel.  # noqa: E501
        :type: object
        """

        self._category = category

    @property
    def description(self):
        """Gets the description of this ToolSpecModel.  # noqa: E501

        Short explanation of what the tool can do.  # noqa: E501

        :return: The description of this ToolSpecModel.  # noqa: E501
        :rtype: object
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ToolSpecModel.

        Short explanation of what the tool can do.  # noqa: E501

        :param description: The description of this ToolSpecModel.  # noqa: E501
        :type: object
        """

        self._description = description

    @property
    def name(self):
        """Gets the name of this ToolSpecModel.  # noqa: E501

        Caller-visible tool name.  # noqa: E501

        :return: The name of this ToolSpecModel.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ToolSpecModel.

        Caller-visible tool name.  # noqa: E501

        :param name: The name of this ToolSpecModel.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def parameters(self):
        """Gets the parameters of this ToolSpecModel.  # noqa: E501

        The tool's declared parameter schema, used to fingerprint its shape. Pre-redact secrets and personal data: this is stored on the learning.  # noqa: E501

        :return: The parameters of this ToolSpecModel.  # noqa: E501
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ToolSpecModel.

        The tool's declared parameter schema, used to fingerprint its shape. Pre-redact secrets and personal data: this is stored on the learning.  # noqa: E501

        :param parameters: The parameters of this ToolSpecModel.  # noqa: E501
        :type: object
        """

        self._parameters = parameters

    @property
    def returns(self):
        """Gets the returns of this ToolSpecModel.  # noqa: E501

        The tool's declared return schema, used to fingerprint its shape. Pre-redact secrets and personal data: this is stored on the learning.  # noqa: E501

        :return: The returns of this ToolSpecModel.  # noqa: E501
        :rtype: object
        """
        return self._returns

    @returns.setter
    def returns(self, returns):
        """Sets the returns of this ToolSpecModel.

        The tool's declared return schema, used to fingerprint its shape. Pre-redact secrets and personal data: this is stored on the learning.  # noqa: E501

        :param returns: The returns of this ToolSpecModel.  # noqa: E501
        :type: object
        """

        self._returns = returns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ToolSpecModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ToolSpecModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
