# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UnavailableClaim(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'claim_id': 'object',
        'is_unavailable': 'object',
        'unavailable_reason': 'object'
    }

    attribute_map = {
        'claim_id': 'claim_id',
        'is_unavailable': 'is_unavailable',
        'unavailable_reason': 'unavailable_reason'
    }

    def __init__(self, claim_id=None, is_unavailable=None, unavailable_reason=None):  # noqa: E501
        """UnavailableClaim - a model defined in Swagger"""  # noqa: E501
        self._claim_id = None
        self._is_unavailable = None
        self._unavailable_reason = None
        self.discriminator = None
        self.claim_id = claim_id
        if is_unavailable is not None:
            self.is_unavailable = is_unavailable
        self.unavailable_reason = unavailable_reason

    @property
    def claim_id(self):
        """Gets the claim_id of this UnavailableClaim.  # noqa: E501


        :return: The claim_id of this UnavailableClaim.  # noqa: E501
        :rtype: object
        """
        return self._claim_id

    @claim_id.setter
    def claim_id(self, claim_id):
        """Sets the claim_id of this UnavailableClaim.


        :param claim_id: The claim_id of this UnavailableClaim.  # noqa: E501
        :type: object
        """
        if claim_id is None:
            raise ValueError("Invalid value for `claim_id`, must not be `None`")  # noqa: E501

        self._claim_id = claim_id

    @property
    def is_unavailable(self):
        """Gets the is_unavailable of this UnavailableClaim.  # noqa: E501


        :return: The is_unavailable of this UnavailableClaim.  # noqa: E501
        :rtype: object
        """
        return self._is_unavailable

    @is_unavailable.setter
    def is_unavailable(self, is_unavailable):
        """Sets the is_unavailable of this UnavailableClaim.


        :param is_unavailable: The is_unavailable of this UnavailableClaim.  # noqa: E501
        :type: object
        """

        self._is_unavailable = is_unavailable

    @property
    def unavailable_reason(self):
        """Gets the unavailable_reason of this UnavailableClaim.  # noqa: E501

        `not_in_read`: a finding or value cites a claim the answer's read did not hold.  # noqa: E501

        :return: The unavailable_reason of this UnavailableClaim.  # noqa: E501
        :rtype: object
        """
        return self._unavailable_reason

    @unavailable_reason.setter
    def unavailable_reason(self, unavailable_reason):
        """Sets the unavailable_reason of this UnavailableClaim.

        `not_in_read`: a finding or value cites a claim the answer's read did not hold.  # noqa: E501

        :param unavailable_reason: The unavailable_reason of this UnavailableClaim.  # noqa: E501
        :type: object
        """
        if unavailable_reason is None:
            raise ValueError("Invalid value for `unavailable_reason`, must not be `None`")  # noqa: E501

        self._unavailable_reason = unavailable_reason

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UnavailableClaim, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnavailableClaim):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
