# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsageRunAggregates(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'run_count': 'object',
        'runs_with_compute_count': 'object',
        'total_compute_seconds': 'object',
        'total_compute_hours': 'object',
        'total_estimated_cost_usd': 'object',
        'total_estimated_compute_cost_usd': 'object',
        'total_estimated_llm_cost_usd': 'object',
        'average_compute_seconds': 'object',
        'unique_session_count': 'object'
    }

    attribute_map = {
        'run_count': 'run_count',
        'runs_with_compute_count': 'runs_with_compute_count',
        'total_compute_seconds': 'total_compute_seconds',
        'total_compute_hours': 'total_compute_hours',
        'total_estimated_cost_usd': 'total_estimated_cost_usd',
        'total_estimated_compute_cost_usd': 'total_estimated_compute_cost_usd',
        'total_estimated_llm_cost_usd': 'total_estimated_llm_cost_usd',
        'average_compute_seconds': 'average_compute_seconds',
        'unique_session_count': 'unique_session_count'
    }

    def __init__(self, run_count=None, runs_with_compute_count=None, total_compute_seconds=None, total_compute_hours=None, total_estimated_cost_usd=None, total_estimated_compute_cost_usd=None, total_estimated_llm_cost_usd=None, average_compute_seconds=None, unique_session_count=None):  # noqa: E501
        """UsageRunAggregates - a model defined in Swagger"""  # noqa: E501
        self._run_count = None
        self._runs_with_compute_count = None
        self._total_compute_seconds = None
        self._total_compute_hours = None
        self._total_estimated_cost_usd = None
        self._total_estimated_compute_cost_usd = None
        self._total_estimated_llm_cost_usd = None
        self._average_compute_seconds = None
        self._unique_session_count = None
        self.discriminator = None
        self.run_count = run_count
        self.runs_with_compute_count = runs_with_compute_count
        self.total_compute_seconds = total_compute_seconds
        self.total_compute_hours = total_compute_hours
        self.total_estimated_cost_usd = total_estimated_cost_usd
        self.total_estimated_compute_cost_usd = total_estimated_compute_cost_usd
        self.total_estimated_llm_cost_usd = total_estimated_llm_cost_usd
        if average_compute_seconds is not None:
            self.average_compute_seconds = average_compute_seconds
        self.unique_session_count = unique_session_count

    @property
    def run_count(self):
        """Gets the run_count of this UsageRunAggregates.  # noqa: E501

        All runs created in the window.  # noqa: E501

        :return: The run_count of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._run_count

    @run_count.setter
    def run_count(self, run_count):
        """Sets the run_count of this UsageRunAggregates.

        All runs created in the window.  # noqa: E501

        :param run_count: The run_count of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if run_count is None:
            raise ValueError("Invalid value for `run_count`, must not be `None`")  # noqa: E501

        self._run_count = run_count

    @property
    def runs_with_compute_count(self):
        """Gets the runs_with_compute_count of this UsageRunAggregates.  # noqa: E501

        Runs with compute_seconds > 0 (used for average duration).  # noqa: E501

        :return: The runs_with_compute_count of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._runs_with_compute_count

    @runs_with_compute_count.setter
    def runs_with_compute_count(self, runs_with_compute_count):
        """Sets the runs_with_compute_count of this UsageRunAggregates.

        Runs with compute_seconds > 0 (used for average duration).  # noqa: E501

        :param runs_with_compute_count: The runs_with_compute_count of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if runs_with_compute_count is None:
            raise ValueError("Invalid value for `runs_with_compute_count`, must not be `None`")  # noqa: E501

        self._runs_with_compute_count = runs_with_compute_count

    @property
    def total_compute_seconds(self):
        """Gets the total_compute_seconds of this UsageRunAggregates.  # noqa: E501

        Sum of compute_seconds for runs in the window.  # noqa: E501

        :return: The total_compute_seconds of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._total_compute_seconds

    @total_compute_seconds.setter
    def total_compute_seconds(self, total_compute_seconds):
        """Sets the total_compute_seconds of this UsageRunAggregates.

        Sum of compute_seconds for runs in the window.  # noqa: E501

        :param total_compute_seconds: The total_compute_seconds of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if total_compute_seconds is None:
            raise ValueError("Invalid value for `total_compute_seconds`, must not be `None`")  # noqa: E501

        self._total_compute_seconds = total_compute_seconds

    @property
    def total_compute_hours(self):
        """Gets the total_compute_hours of this UsageRunAggregates.  # noqa: E501

        total_compute_seconds / 3600.  # noqa: E501

        :return: The total_compute_hours of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._total_compute_hours

    @total_compute_hours.setter
    def total_compute_hours(self, total_compute_hours):
        """Sets the total_compute_hours of this UsageRunAggregates.

        total_compute_seconds / 3600.  # noqa: E501

        :param total_compute_hours: The total_compute_hours of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if total_compute_hours is None:
            raise ValueError("Invalid value for `total_compute_hours`, must not be `None`")  # noqa: E501

        self._total_compute_hours = total_compute_hours

    @property
    def total_estimated_cost_usd(self):
        """Gets the total_estimated_cost_usd of this UsageRunAggregates.  # noqa: E501

        Sum of estimated_total_cost_usd (ledger values at completion time).  # noqa: E501

        :return: The total_estimated_cost_usd of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._total_estimated_cost_usd

    @total_estimated_cost_usd.setter
    def total_estimated_cost_usd(self, total_estimated_cost_usd):
        """Sets the total_estimated_cost_usd of this UsageRunAggregates.

        Sum of estimated_total_cost_usd (ledger values at completion time).  # noqa: E501

        :param total_estimated_cost_usd: The total_estimated_cost_usd of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if total_estimated_cost_usd is None:
            raise ValueError("Invalid value for `total_estimated_cost_usd`, must not be `None`")  # noqa: E501

        self._total_estimated_cost_usd = total_estimated_cost_usd

    @property
    def total_estimated_compute_cost_usd(self):
        """Gets the total_estimated_compute_cost_usd of this UsageRunAggregates.  # noqa: E501

        Sum of estimated_compute_cost_usd.  # noqa: E501

        :return: The total_estimated_compute_cost_usd of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._total_estimated_compute_cost_usd

    @total_estimated_compute_cost_usd.setter
    def total_estimated_compute_cost_usd(self, total_estimated_compute_cost_usd):
        """Sets the total_estimated_compute_cost_usd of this UsageRunAggregates.

        Sum of estimated_compute_cost_usd.  # noqa: E501

        :param total_estimated_compute_cost_usd: The total_estimated_compute_cost_usd of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if total_estimated_compute_cost_usd is None:
            raise ValueError("Invalid value for `total_estimated_compute_cost_usd`, must not be `None`")  # noqa: E501

        self._total_estimated_compute_cost_usd = total_estimated_compute_cost_usd

    @property
    def total_estimated_llm_cost_usd(self):
        """Gets the total_estimated_llm_cost_usd of this UsageRunAggregates.  # noqa: E501

        Sum of estimated_llm_cost_usd.  # noqa: E501

        :return: The total_estimated_llm_cost_usd of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._total_estimated_llm_cost_usd

    @total_estimated_llm_cost_usd.setter
    def total_estimated_llm_cost_usd(self, total_estimated_llm_cost_usd):
        """Sets the total_estimated_llm_cost_usd of this UsageRunAggregates.

        Sum of estimated_llm_cost_usd.  # noqa: E501

        :param total_estimated_llm_cost_usd: The total_estimated_llm_cost_usd of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if total_estimated_llm_cost_usd is None:
            raise ValueError("Invalid value for `total_estimated_llm_cost_usd`, must not be `None`")  # noqa: E501

        self._total_estimated_llm_cost_usd = total_estimated_llm_cost_usd

    @property
    def average_compute_seconds(self):
        """Gets the average_compute_seconds of this UsageRunAggregates.  # noqa: E501

        Mean compute_seconds over runs with compute > 0; null if none.  # noqa: E501

        :return: The average_compute_seconds of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._average_compute_seconds

    @average_compute_seconds.setter
    def average_compute_seconds(self, average_compute_seconds):
        """Sets the average_compute_seconds of this UsageRunAggregates.

        Mean compute_seconds over runs with compute > 0; null if none.  # noqa: E501

        :param average_compute_seconds: The average_compute_seconds of this UsageRunAggregates.  # noqa: E501
        :type: object
        """

        self._average_compute_seconds = average_compute_seconds

    @property
    def unique_session_count(self):
        """Gets the unique_session_count of this UsageRunAggregates.  # noqa: E501

        Distinct non-null session_id values in the window.  # noqa: E501

        :return: The unique_session_count of this UsageRunAggregates.  # noqa: E501
        :rtype: object
        """
        return self._unique_session_count

    @unique_session_count.setter
    def unique_session_count(self, unique_session_count):
        """Sets the unique_session_count of this UsageRunAggregates.

        Distinct non-null session_id values in the window.  # noqa: E501

        :param unique_session_count: The unique_session_count of this UsageRunAggregates.  # noqa: E501
        :type: object
        """
        if unique_session_count is None:
            raise ValueError("Invalid value for `unique_session_count`, must not be `None`")  # noqa: E501

        self._unique_session_count = unique_session_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsageRunAggregates, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsageRunAggregates):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
