# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UsageLlmCallItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'model_id': 'object',
        'component': 'object',
        'prompt_tokens': 'object',
        'completion_tokens': 'object',
        'total_tokens': 'object',
        'cost_usd': 'object',
        'recorded_at': 'object'
    }

    attribute_map = {
        'id': 'id',
        'model_id': 'model_id',
        'component': 'component',
        'prompt_tokens': 'prompt_tokens',
        'completion_tokens': 'completion_tokens',
        'total_tokens': 'total_tokens',
        'cost_usd': 'cost_usd',
        'recorded_at': 'recorded_at'
    }

    def __init__(self, id=None, model_id=None, component=None, prompt_tokens=None, completion_tokens=None, total_tokens=None, cost_usd=None, recorded_at=None):  # noqa: E501
        """UsageLlmCallItem - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._model_id = None
        self._component = None
        self._prompt_tokens = None
        self._completion_tokens = None
        self._total_tokens = None
        self._cost_usd = None
        self._recorded_at = None
        self.discriminator = None
        self.id = id
        self.model_id = model_id
        self.component = component
        self.prompt_tokens = prompt_tokens
        self.completion_tokens = completion_tokens
        self.total_tokens = total_tokens
        if cost_usd is not None:
            self.cost_usd = cost_usd
        self.recorded_at = recorded_at

    @property
    def id(self):
        """Gets the id of this UsageLlmCallItem.  # noqa: E501


        :return: The id of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UsageLlmCallItem.


        :param id: The id of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def model_id(self):
        """Gets the model_id of this UsageLlmCallItem.  # noqa: E501


        :return: The model_id of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this UsageLlmCallItem.


        :param model_id: The model_id of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if model_id is None:
            raise ValueError("Invalid value for `model_id`, must not be `None`")  # noqa: E501

        self._model_id = model_id

    @property
    def component(self):
        """Gets the component of this UsageLlmCallItem.  # noqa: E501


        :return: The component of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this UsageLlmCallItem.


        :param component: The component of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if component is None:
            raise ValueError("Invalid value for `component`, must not be `None`")  # noqa: E501

        self._component = component

    @property
    def prompt_tokens(self):
        """Gets the prompt_tokens of this UsageLlmCallItem.  # noqa: E501


        :return: The prompt_tokens of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._prompt_tokens

    @prompt_tokens.setter
    def prompt_tokens(self, prompt_tokens):
        """Sets the prompt_tokens of this UsageLlmCallItem.


        :param prompt_tokens: The prompt_tokens of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if prompt_tokens is None:
            raise ValueError("Invalid value for `prompt_tokens`, must not be `None`")  # noqa: E501

        self._prompt_tokens = prompt_tokens

    @property
    def completion_tokens(self):
        """Gets the completion_tokens of this UsageLlmCallItem.  # noqa: E501


        :return: The completion_tokens of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._completion_tokens

    @completion_tokens.setter
    def completion_tokens(self, completion_tokens):
        """Sets the completion_tokens of this UsageLlmCallItem.


        :param completion_tokens: The completion_tokens of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if completion_tokens is None:
            raise ValueError("Invalid value for `completion_tokens`, must not be `None`")  # noqa: E501

        self._completion_tokens = completion_tokens

    @property
    def total_tokens(self):
        """Gets the total_tokens of this UsageLlmCallItem.  # noqa: E501


        :return: The total_tokens of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._total_tokens

    @total_tokens.setter
    def total_tokens(self, total_tokens):
        """Sets the total_tokens of this UsageLlmCallItem.


        :param total_tokens: The total_tokens of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if total_tokens is None:
            raise ValueError("Invalid value for `total_tokens`, must not be `None`")  # noqa: E501

        self._total_tokens = total_tokens

    @property
    def cost_usd(self):
        """Gets the cost_usd of this UsageLlmCallItem.  # noqa: E501

        Raw provider cost for this call; null when not recorded.  # noqa: E501

        :return: The cost_usd of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._cost_usd

    @cost_usd.setter
    def cost_usd(self, cost_usd):
        """Sets the cost_usd of this UsageLlmCallItem.

        Raw provider cost for this call; null when not recorded.  # noqa: E501

        :param cost_usd: The cost_usd of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """

        self._cost_usd = cost_usd

    @property
    def recorded_at(self):
        """Gets the recorded_at of this UsageLlmCallItem.  # noqa: E501


        :return: The recorded_at of this UsageLlmCallItem.  # noqa: E501
        :rtype: object
        """
        return self._recorded_at

    @recorded_at.setter
    def recorded_at(self, recorded_at):
        """Sets the recorded_at of this UsageLlmCallItem.


        :param recorded_at: The recorded_at of this UsageLlmCallItem.  # noqa: E501
        :type: object
        """
        if recorded_at is None:
            raise ValueError("Invalid value for `recorded_at`, must not be `None`")  # noqa: E501

        self._recorded_at = recorded_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UsageLlmCallItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsageLlmCallItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
