# coding: utf-8

"""
    Hyperstruck Core

    Hyperstruck Core management API  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WorkOSPortalLinkRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'intent': 'object',
        'return_url': 'object'
    }

    attribute_map = {
        'intent': 'intent',
        'return_url': 'return_url'
    }

    def __init__(self, intent=None, return_url=None):  # noqa: E501
        """WorkOSPortalLinkRequest - a model defined in Swagger"""  # noqa: E501
        self._intent = None
        self._return_url = None
        self.discriminator = None
        self.intent = intent
        if return_url is not None:
            self.return_url = return_url

    @property
    def intent(self):
        """Gets the intent of this WorkOSPortalLinkRequest.  # noqa: E501


        :return: The intent of this WorkOSPortalLinkRequest.  # noqa: E501
        :rtype: object
        """
        return self._intent

    @intent.setter
    def intent(self, intent):
        """Sets the intent of this WorkOSPortalLinkRequest.


        :param intent: The intent of this WorkOSPortalLinkRequest.  # noqa: E501
        :type: object
        """
        if intent is None:
            raise ValueError("Invalid value for `intent`, must not be `None`")  # noqa: E501

        self._intent = intent

    @property
    def return_url(self):
        """Gets the return_url of this WorkOSPortalLinkRequest.  # noqa: E501


        :return: The return_url of this WorkOSPortalLinkRequest.  # noqa: E501
        :rtype: object
        """
        return self._return_url

    @return_url.setter
    def return_url(self, return_url):
        """Sets the return_url of this WorkOSPortalLinkRequest.


        :param return_url: The return_url of this WorkOSPortalLinkRequest.  # noqa: E501
        :type: object
        """

        self._return_url = return_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WorkOSPortalLinkRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkOSPortalLinkRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
