# coding: utf-8

"""
    Hyperstruck Core

    Create and operate hosted agents, runs, learnings, and integrations. Authenticate resource requests with a Bearer API key unless an endpoint explicitly requires a portal session.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from hyperstruck.api_client import ApiClient


class ReportingApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def chart_data_endpoint_reporting_charts_chart_id_data_post(self, chart_id, **kwargs):  # noqa: E501
        """Run Chart Data  # noqa: E501

        Run the stored query_binding for a visible chart (Mode B).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.chart_data_endpoint_reporting_charts_chart_id_data_post(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :param object body:
        :return: ReportingQueryResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.chart_data_endpoint_reporting_charts_chart_id_data_post_with_http_info(chart_id, **kwargs)  # noqa: E501
        else:
            (data) = self.chart_data_endpoint_reporting_charts_chart_id_data_post_with_http_info(chart_id, **kwargs)  # noqa: E501
            return data

    def chart_data_endpoint_reporting_charts_chart_id_data_post_with_http_info(self, chart_id, **kwargs):  # noqa: E501
        """Run Chart Data  # noqa: E501

        Run the stored query_binding for a visible chart (Mode B).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.chart_data_endpoint_reporting_charts_chart_id_data_post_with_http_info(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :param object body:
        :return: ReportingQueryResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['chart_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method chart_data_endpoint_reporting_charts_chart_id_data_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'chart_id' is set
        if ('chart_id' not in params or
                params['chart_id'] is None):
            raise ValueError("Missing the required parameter `chart_id` when calling `chart_data_endpoint_reporting_charts_chart_id_data_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'chart_id' in params:
            path_params['chart_id'] = params['chart_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts/{chart_id}/data', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ReportingQueryResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_chart_endpoint_reporting_charts_post(self, body, **kwargs):  # noqa: E501
        """Create Chart  # noqa: E501

        Create a chart in a space (portal: private to the user until published; API key: null-owner draft shared among keys in the tenant). Requires can_publish on the space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_chart_endpoint_reporting_charts_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ChartCreateRequest body: (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_chart_endpoint_reporting_charts_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_chart_endpoint_reporting_charts_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_chart_endpoint_reporting_charts_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create Chart  # noqa: E501

        Create a chart in a space (portal: private to the user until published; API key: null-owner draft shared among keys in the tenant). Requires can_publish on the space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_chart_endpoint_reporting_charts_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ChartCreateRequest body: (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_chart_endpoint_reporting_charts_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_chart_endpoint_reporting_charts_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ChartResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_dashboard_endpoint_reporting_dashboards_post(self, body, **kwargs):  # noqa: E501
        """Create Dashboard  # noqa: E501

        Create an empty multi-chart dashboard in a space. Requires can_publish on the space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_dashboard_endpoint_reporting_dashboards_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardCreateRequest body: (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_dashboard_endpoint_reporting_dashboards_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_dashboard_endpoint_reporting_dashboards_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_dashboard_endpoint_reporting_dashboards_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create Dashboard  # noqa: E501

        Create an empty multi-chart dashboard in a space. Requires can_publish on the space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_dashboard_endpoint_reporting_dashboards_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardCreateRequest body: (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_dashboard_endpoint_reporting_dashboards_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_dashboard_endpoint_reporting_dashboards_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DashboardResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_chart_endpoint_reporting_charts_chart_id_delete(self, chart_id, **kwargs):  # noqa: E501
        """Delete Chart  # noqa: E501

        Delete a visible chart. Charts linked on dashboards are removed from those canvases via cascade. Requires can_publish on the chart's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_chart_endpoint_reporting_charts_chart_id_delete(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_chart_endpoint_reporting_charts_chart_id_delete_with_http_info(chart_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_chart_endpoint_reporting_charts_chart_id_delete_with_http_info(chart_id, **kwargs)  # noqa: E501
            return data

    def delete_chart_endpoint_reporting_charts_chart_id_delete_with_http_info(self, chart_id, **kwargs):  # noqa: E501
        """Delete Chart  # noqa: E501

        Delete a visible chart. Charts linked on dashboards are removed from those canvases via cascade. Requires can_publish on the chart's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_chart_endpoint_reporting_charts_chart_id_delete_with_http_info(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['chart_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_chart_endpoint_reporting_charts_chart_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'chart_id' is set
        if ('chart_id' not in params or
                params['chart_id'] is None):
            raise ValueError("Missing the required parameter `chart_id` when calling `delete_chart_endpoint_reporting_charts_chart_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'chart_id' in params:
            path_params['chart_id'] = params['chart_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts/{chart_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete(self, dashboard_id, **kwargs):  # noqa: E501
        """Delete Dashboard  # noqa: E501

        Delete a dashboard and its placements. Charts themselves are kept. Requires can_publish on the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete(dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete_with_http_info(dashboard_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete_with_http_info(dashboard_id, **kwargs)  # noqa: E501
            return data

    def delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete_with_http_info(self, dashboard_id, **kwargs):  # noqa: E501
        """Delete Dashboard  # noqa: E501

        Delete a dashboard and its placements. Charts themselves are kept. Requires can_publish on the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete_with_http_info(dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['dashboard_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'dashboard_id' is set
        if ('dashboard_id' not in params or
                params['dashboard_id'] is None):
            raise ValueError("Missing the required parameter `dashboard_id` when calling `delete_dashboard_endpoint_reporting_dashboards_dashboard_id_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dashboard_id' in params:
            path_params['dashboard_id'] = params['dashboard_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards/{dashboard_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_chart_endpoint_reporting_charts_chart_id_get(self, chart_id, **kwargs):  # noqa: E501
        """Get Chart  # noqa: E501

        Return a chart the caller can see: their own draft, a tenant-shared API-key draft, or a chart linked on a readable dashboard.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_chart_endpoint_reporting_charts_chart_id_get(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_chart_endpoint_reporting_charts_chart_id_get_with_http_info(chart_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_chart_endpoint_reporting_charts_chart_id_get_with_http_info(chart_id, **kwargs)  # noqa: E501
            return data

    def get_chart_endpoint_reporting_charts_chart_id_get_with_http_info(self, chart_id, **kwargs):  # noqa: E501
        """Get Chart  # noqa: E501

        Return a chart the caller can see: their own draft, a tenant-shared API-key draft, or a chart linked on a readable dashboard.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_chart_endpoint_reporting_charts_chart_id_get_with_http_info(chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['chart_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_chart_endpoint_reporting_charts_chart_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'chart_id' is set
        if ('chart_id' not in params or
                params['chart_id'] is None):
            raise ValueError("Missing the required parameter `chart_id` when calling `get_chart_endpoint_reporting_charts_chart_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'chart_id' in params:
            path_params['chart_id'] = params['chart_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts/{chart_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ChartResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_dashboard_endpoint_reporting_dashboards_dashboard_id_get(self, dashboard_id, **kwargs):  # noqa: E501
        """Get Dashboard  # noqa: E501

        Return a dashboard and its chart placements when the caller can read the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_dashboard_endpoint_reporting_dashboards_dashboard_id_get(dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_dashboard_endpoint_reporting_dashboards_dashboard_id_get_with_http_info(dashboard_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_dashboard_endpoint_reporting_dashboards_dashboard_id_get_with_http_info(dashboard_id, **kwargs)  # noqa: E501
            return data

    def get_dashboard_endpoint_reporting_dashboards_dashboard_id_get_with_http_info(self, dashboard_id, **kwargs):  # noqa: E501
        """Get Dashboard  # noqa: E501

        Return a dashboard and its chart placements when the caller can read the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_dashboard_endpoint_reporting_dashboards_dashboard_id_get_with_http_info(dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['dashboard_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_dashboard_endpoint_reporting_dashboards_dashboard_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'dashboard_id' is set
        if ('dashboard_id' not in params or
                params['dashboard_id'] is None):
            raise ValueError("Missing the required parameter `dashboard_id` when calling `get_dashboard_endpoint_reporting_dashboards_dashboard_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dashboard_id' in params:
            path_params['dashboard_id'] = params['dashboard_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards/{dashboard_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DashboardResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_defaults_endpoint_reporting_defaults_space_id_get(self, space_id, **kwargs):  # noqa: E501
        """Get Reporting Defaults  # noqa: E501

        Return space hyperparameters used to derive dollar measures. Missing rows fall back to product defaults. Requires space viewer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_defaults_endpoint_reporting_defaults_space_id_get(space_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id: Space UUID returned by the spaces list or create endpoint. (required)
        :return: ReportingDefaultsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_defaults_endpoint_reporting_defaults_space_id_get_with_http_info(space_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_defaults_endpoint_reporting_defaults_space_id_get_with_http_info(space_id, **kwargs)  # noqa: E501
            return data

    def get_defaults_endpoint_reporting_defaults_space_id_get_with_http_info(self, space_id, **kwargs):  # noqa: E501
        """Get Reporting Defaults  # noqa: E501

        Return space hyperparameters used to derive dollar measures. Missing rows fall back to product defaults. Requires space viewer.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_defaults_endpoint_reporting_defaults_space_id_get_with_http_info(space_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id: Space UUID returned by the spaces list or create endpoint. (required)
        :return: ReportingDefaultsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['space_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_defaults_endpoint_reporting_defaults_space_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'space_id' is set
        if ('space_id' not in params or
                params['space_id'] is None):
            raise ValueError("Missing the required parameter `space_id` when calling `get_defaults_endpoint_reporting_defaults_space_id_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'space_id' in params:
            path_params['space_id'] = params['space_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/defaults/{space_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ReportingDefaultsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_metric_catalog_endpoint_reporting_metric_catalog_get(self, **kwargs):  # noqa: E501
        """Get Metric Catalog  # noqa: E501

        Starter dimensions and measures for Graphic Walker field pickers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_metric_catalog_endpoint_reporting_metric_catalog_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: MetricCatalogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_metric_catalog_endpoint_reporting_metric_catalog_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_metric_catalog_endpoint_reporting_metric_catalog_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_metric_catalog_endpoint_reporting_metric_catalog_get_with_http_info(self, **kwargs):  # noqa: E501
        """Get Metric Catalog  # noqa: E501

        Starter dimensions and measures for Graphic Walker field pickers.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_metric_catalog_endpoint_reporting_metric_catalog_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: MetricCatalogResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_metric_catalog_endpoint_reporting_metric_catalog_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/metric-catalog', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='MetricCatalogResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_charts_endpoint_reporting_charts_get(self, **kwargs):  # noqa: E501
        """List Charts  # noqa: E501

        List charts visible to the caller: portal users see their own drafts plus charts linked on a dashboard in a readable space; API keys see tenant-shared null-owner drafts plus those published charts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_charts_endpoint_reporting_charts_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id:
        :return: ChartListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_charts_endpoint_reporting_charts_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.list_charts_endpoint_reporting_charts_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_charts_endpoint_reporting_charts_get_with_http_info(self, **kwargs):  # noqa: E501
        """List Charts  # noqa: E501

        List charts visible to the caller: portal users see their own drafts plus charts linked on a dashboard in a readable space; API keys see tenant-shared null-owner drafts plus those published charts.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_charts_endpoint_reporting_charts_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id:
        :return: ChartListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['space_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_charts_endpoint_reporting_charts_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'space_id' in params:
            query_params.append(('space_id', params['space_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ChartListResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def list_dashboards_endpoint_reporting_dashboards_get(self, **kwargs):  # noqa: E501
        """List Dashboards  # noqa: E501

        List multi-chart dashboards in spaces the caller can read. Optionally filter with `space_id`.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_dashboards_endpoint_reporting_dashboards_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id:
        :return: DashboardListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.list_dashboards_endpoint_reporting_dashboards_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.list_dashboards_endpoint_reporting_dashboards_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def list_dashboards_endpoint_reporting_dashboards_get_with_http_info(self, **kwargs):  # noqa: E501
        """List Dashboards  # noqa: E501

        List multi-chart dashboards in spaces the caller can read. Optionally filter with `space_id`.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.list_dashboards_endpoint_reporting_dashboards_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param object space_id:
        :return: DashboardListResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['space_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_dashboards_endpoint_reporting_dashboards_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'space_id' in params:
            query_params.append(('space_id', params['space_id']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DashboardListResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put(self, body, dashboard_id, **kwargs):  # noqa: E501
        """Replace Dashboard Items  # noqa: E501

        Replace all chart placements on a dashboard. Linking a chart publishes it to space viewers. Validates col_index + col_span <= columns.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put(body, dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardItemsPutRequest body: (required)
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put_with_http_info(body, dashboard_id, **kwargs)  # noqa: E501
        else:
            (data) = self.put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put_with_http_info(body, dashboard_id, **kwargs)  # noqa: E501
            return data

    def put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put_with_http_info(self, body, dashboard_id, **kwargs):  # noqa: E501
        """Replace Dashboard Items  # noqa: E501

        Replace all chart placements on a dashboard. Linking a chart publishes it to space viewers. Validates col_index + col_span <= columns.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put_with_http_info(body, dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardItemsPutRequest body: (required)
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'dashboard_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put`")  # noqa: E501
        # verify the required parameter 'dashboard_id' is set
        if ('dashboard_id' not in params or
                params['dashboard_id'] is None):
            raise ValueError("Missing the required parameter `dashboard_id` when calling `put_dashboard_items_endpoint_reporting_dashboards_dashboard_id_items_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dashboard_id' in params:
            path_params['dashboard_id'] = params['dashboard_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards/{dashboard_id}/items', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DashboardResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_defaults_endpoint_reporting_defaults_space_id_put(self, body, space_id, **kwargs):  # noqa: E501
        """Put Reporting Defaults  # noqa: E501

        Replace space hyperparameters. Requires space steward (organization admins also qualify as stewards).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_defaults_endpoint_reporting_defaults_space_id_put(body, space_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ReportingDefaultsPutRequest body: (required)
        :param object space_id: Space UUID returned by the spaces list or create endpoint. (required)
        :return: ReportingDefaultsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_defaults_endpoint_reporting_defaults_space_id_put_with_http_info(body, space_id, **kwargs)  # noqa: E501
        else:
            (data) = self.put_defaults_endpoint_reporting_defaults_space_id_put_with_http_info(body, space_id, **kwargs)  # noqa: E501
            return data

    def put_defaults_endpoint_reporting_defaults_space_id_put_with_http_info(self, body, space_id, **kwargs):  # noqa: E501
        """Put Reporting Defaults  # noqa: E501

        Replace space hyperparameters. Requires space steward (organization admins also qualify as stewards).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_defaults_endpoint_reporting_defaults_space_id_put_with_http_info(body, space_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ReportingDefaultsPutRequest body: (required)
        :param object space_id: Space UUID returned by the spaces list or create endpoint. (required)
        :return: ReportingDefaultsResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'space_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_defaults_endpoint_reporting_defaults_space_id_put" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `put_defaults_endpoint_reporting_defaults_space_id_put`")  # noqa: E501
        # verify the required parameter 'space_id' is set
        if ('space_id' not in params or
                params['space_id'] is None):
            raise ValueError("Missing the required parameter `space_id` when calling `put_defaults_endpoint_reporting_defaults_space_id_put`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'space_id' in params:
            path_params['space_id'] = params['space_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/defaults/{space_id}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ReportingDefaultsResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reporting_query_endpoint_reporting_query_post(self, body, **kwargs):  # noqa: E501
        """Run Reporting Query  # noqa: E501

        Mode B: server-side aggregate of daily reporting facts for a query binding. Dollar measures are derived at read time from space defaults.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reporting_query_endpoint_reporting_query_post(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ReportingQueryRequest body: (required)
        :return: ReportingQueryResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.reporting_query_endpoint_reporting_query_post_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.reporting_query_endpoint_reporting_query_post_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def reporting_query_endpoint_reporting_query_post_with_http_info(self, body, **kwargs):  # noqa: E501
        """Run Reporting Query  # noqa: E501

        Mode B: server-side aggregate of daily reporting facts for a query binding. Dollar measures are derived at read time from space defaults.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reporting_query_endpoint_reporting_query_post_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ReportingQueryRequest body: (required)
        :return: ReportingQueryResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reporting_query_endpoint_reporting_query_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `reporting_query_endpoint_reporting_query_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/query', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ReportingQueryResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_chart_endpoint_reporting_charts_chart_id_patch(self, body, chart_id, **kwargs):  # noqa: E501
        """Update Chart  # noqa: E501

        Update title, description, viz spec, or query binding for a visible chart. Requires can_publish on the chart's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_chart_endpoint_reporting_charts_chart_id_patch(body, chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ChartUpdateRequest body: (required)
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_chart_endpoint_reporting_charts_chart_id_patch_with_http_info(body, chart_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_chart_endpoint_reporting_charts_chart_id_patch_with_http_info(body, chart_id, **kwargs)  # noqa: E501
            return data

    def update_chart_endpoint_reporting_charts_chart_id_patch_with_http_info(self, body, chart_id, **kwargs):  # noqa: E501
        """Update Chart  # noqa: E501

        Update title, description, viz spec, or query binding for a visible chart. Requires can_publish on the chart's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_chart_endpoint_reporting_charts_chart_id_patch_with_http_info(body, chart_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ChartUpdateRequest body: (required)
        :param object chart_id: Reporting chart UUID returned by the chart create or list endpoint. (required)
        :return: ChartResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'chart_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_chart_endpoint_reporting_charts_chart_id_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_chart_endpoint_reporting_charts_chart_id_patch`")  # noqa: E501
        # verify the required parameter 'chart_id' is set
        if ('chart_id' not in params or
                params['chart_id'] is None):
            raise ValueError("Missing the required parameter `chart_id` when calling `update_chart_endpoint_reporting_charts_chart_id_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'chart_id' in params:
            path_params['chart_id'] = params['chart_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/charts/{chart_id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ChartResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch(self, body, dashboard_id, **kwargs):  # noqa: E501
        """Update Dashboard  # noqa: E501

        Update dashboard metadata such as title, description, columns, or window preset. Requires can_publish on the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch(body, dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardUpdateRequest body: (required)
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch_with_http_info(body, dashboard_id, **kwargs)  # noqa: E501
        else:
            (data) = self.update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch_with_http_info(body, dashboard_id, **kwargs)  # noqa: E501
            return data

    def update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch_with_http_info(self, body, dashboard_id, **kwargs):  # noqa: E501
        """Update Dashboard  # noqa: E501

        Update dashboard metadata such as title, description, columns, or window preset. Requires can_publish on the dashboard's space.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch_with_http_info(body, dashboard_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param DashboardUpdateRequest body: (required)
        :param object dashboard_id: Reporting dashboard UUID returned by the dashboard create or list endpoint. (required)
        :return: DashboardResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'dashboard_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch`")  # noqa: E501
        # verify the required parameter 'dashboard_id' is set
        if ('dashboard_id' not in params or
                params['dashboard_id'] is None):
            raise ValueError("Missing the required parameter `dashboard_id` when calling `update_dashboard_endpoint_reporting_dashboards_dashboard_id_patch`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'dashboard_id' in params:
            path_params['dashboard_id'] = params['dashboard_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BearerApiKey']  # noqa: E501

        return self.api_client.call_api(
            '/reporting/dashboards/{dashboard_id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='DashboardResponse',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
